import type {TableColumnType} from "../../../../../../../components/others/Table/TableExports.ts";
import RenderTypes from "../../../../../../../components/others/Table/constances/renderTypes.ts";
import TABLE_RENDER_TYPES from "../../../../../../../components/others/Table/constances/renderTypes.ts";

export const JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS = {
  CUSTOMER_NUMBER: 'customerNumber',
  CUSTOMER_TYPE: 'customerType',
  NATIONALITY: 'nationality',
  NAME: 'name',
  IDENTIFICATION_CODE: 'identificationCode',
  SHEHAB_ID: 'shehabId',
  LAST_CUSTOMER_UPDATE_DATE: 'lastCustomerUpdateDate',
  CUSTOMER_BRANCH_CODE: 'customerBranchCode',
  BRANCH_NAME: 'branchName',
  CUSTOMER_REGION_CODE: 'customerRegionCode',
  REGION_NAME: 'regionName',
} as const;

export const JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS: TableColumnType[] = [
  {
    label: 'شماره مشتری',
    accessor: JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.CUSTOMER_NUMBER,
  },
  {
    label: 'نوع مشتری',
    accessor: JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.CUSTOMER_TYPE,
  },
  {
    label: 'ملیت',
    accessor: JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.NATIONALITY,
  },
  {
    label: 'نام و نام خانوادگی / نام شرکت/موسسه',
    accessor: JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.NAME,
  },
  {
    label: 'کدملی/شناسه فراگیر اتباع/شناسه ملی',
    accessor: JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.IDENTIFICATION_CODE,
  },
  {
    label: 'شناسه شهاب',
    accessor: JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.SHEHAB_ID,
  },
  {
    label: 'تاریخ آخرین تغییرات تعریف مشتری',
    accessor: JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.LAST_CUSTOMER_UPDATE_DATE,
  },
  {
    label: 'کدشعبه تعریف مشتری',
    accessor: JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.CUSTOMER_BRANCH_CODE,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
  {
    label: 'نام شعبه',
    accessor: JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.BRANCH_NAME,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
  {
    label: 'کد منطقه تعریف مشتری',
    accessor: JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.CUSTOMER_REGION_CODE,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
  {
    label: 'نام منطقه',
    accessor: JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.REGION_NAME,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
];

export const JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_FAKE_DATA = [
  {
    id: 1,
    [JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.CUSTOMER_NUMBER]: '10452367',
    [JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.CUSTOMER_TYPE]: 'حقیقی',
    [JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.NATIONALITY]: 'ایرانی',
    [JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.NAME]: 'علی رضایی',
    [JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.IDENTIFICATION_CODE]: '1234567890',
    [JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.SHEHAB_ID]: 'SHB-458721',
    [JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.LAST_CUSTOMER_UPDATE_DATE]: '1402/11/05',
    [JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.CUSTOMER_BRANCH_CODE]: '1101',
    [JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.BRANCH_NAME]: 'شعبه مرکزی',
    [JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.CUSTOMER_REGION_CODE]: '01',
    [JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.REGION_NAME]: 'منطقه شمال',
  },
  {
    id: 2,
    [JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.CUSTOMER_NUMBER]: '20984511',
    [JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.CUSTOMER_TYPE]: 'حقوقی',
    [JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.NATIONALITY]: 'ایرانی',
    [JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.NAME]: 'شرکت توسعه تجارت پارس',
    [JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.IDENTIFICATION_CODE]: '14012345678',
    [JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.SHEHAB_ID]: 'SHB-998452',
    [JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.LAST_CUSTOMER_UPDATE_DATE]: '1403/01/18',
    [JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.CUSTOMER_BRANCH_CODE]: '2210',
    [JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.BRANCH_NAME]: 'شعبه ولیعصر',
    [JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.CUSTOMER_REGION_CODE]: '03',
    [JOINT_ACCOUNT_JOINT_ACCOUNT_MEMBERS_TABLE_COLUMNS_KEYS.REGION_NAME]: 'منطقه غرب',
  },
];
