import type {TableColumnType} from "../../../../../../../components/others/Table/TableExports.ts";

export const INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS = {
  MOBILE_NUMBER: 'mobileNumber',
  OWNER_TYPE: 'ownerType',
  FIRST_NAME: 'firstName',
  LAST_NAME: 'lastName',
  NATIONAL_ID: 'nationalId',
  COMPANY_NAME: 'companyName',
  NATIONAL_COMPANY_ID: 'nationalCompanyId',
} as const;

export const INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS: TableColumnType[] = [
  {
    label: 'شماره موبایل',
    accessor: INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.MOBILE_NUMBER,
  },
  {
    label: 'نوع صاحب موبایل',
    accessor: INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.OWNER_TYPE,
  },
  {
    label: 'نام',
    accessor: INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.FIRST_NAME,
  },
  {
    label: 'نام خانوادگی',
    accessor: INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.LAST_NAME,
  },
  {
    label: 'کدملی/شناسه فراگیر اتباع',
    accessor: INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.NATIONAL_ID,
  },
  {
    label: 'نام شرکت',
    accessor: INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.COMPANY_NAME,
  },
  {
    label: 'شناسه ملی',
    accessor: INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.NATIONAL_COMPANY_ID,
  },
];

export const INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_FAKE_DATA = [
  {
    id: 1,
    [INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.MOBILE_NUMBER]: '09121234567',
    [INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.OWNER_TYPE]: 'حقیقی',
    [INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.FIRST_NAME]: 'علی',
    [INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.LAST_NAME]: 'محمدی',
    [INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.NATIONAL_ID]: '1234567890',
    [INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.COMPANY_NAME]: '-',
    [INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.NATIONAL_COMPANY_ID]: '-',
  },
  {
    id: 2,
    [INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.MOBILE_NUMBER]: '09351234567',
    [INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.OWNER_TYPE]: 'حقوقی',
    [INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.FIRST_NAME]: '-',
    [INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.LAST_NAME]: '-',
    [INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.NATIONAL_ID]: '-',
    [INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.COMPANY_NAME]: 'شرکت فناوری پارس',
    [INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.NATIONAL_COMPANY_ID]: '14001234567',
  },
  {
    id: 3,
    [INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.MOBILE_NUMBER]: '09011234567',
    [INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.OWNER_TYPE]: 'حقیقی',
    [INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.FIRST_NAME]: 'مریم',
    [INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.LAST_NAME]: 'رضایی',
    [INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.NATIONAL_ID]: '9876543210',
    [INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.COMPANY_NAME]: '-',
    [INDIVIDUAL_ACCOUNT_SAPTA_MOBILE_NUMBERS_TABLE_COLUMNS_KEYS.NATIONAL_COMPANY_ID]: '-',
  },
];
