import type {TableColumnType} from "../../../../../../components/others/Table/TableExports.ts";
import type {TabsProps} from "../../../../../../components/others/Tab/Tab.tsx";

export const PANEL_INDIVIDUAL_BANKING_COMMITMENTS_DETAIL_TABS_KEYS = {
  BENEFICIARIES: 'beneficiaries',
  GUARANTORS: 'guarantors',
}

export const PANEL_INDIVIDUAL_BANKING_COMMITMENTS_DETAIL_TABS: TabsProps['tabs'] = [
  {
    id: PANEL_INDIVIDUAL_BANKING_COMMITMENTS_DETAIL_TABS_KEYS.BENEFICIARIES,
    title: 'ذینفعان'
  },
  {
    id: PANEL_INDIVIDUAL_BANKING_COMMITMENTS_DETAIL_TABS_KEYS.GUARANTORS,
    title: 'ضامنین'
  },
]

export const PANEL_INDIVIDUAL_COMMITMENT_DETAIL_TABLE_COLUMNS_KEYS = {
  CUSTOMER_NUMBER: 'customerNumber',
  CUSTOMER_TYPE: 'customerType',
  FIRST_NAME: 'firstName',
  LAST_NAME: 'lastName',
  NATIONAL_ID: 'nationalId',
  COMPANY_NAME: 'companyName',
  CHECK_RETURN_DATE: 'checkReturnDate',
  NATIONAL_COMPANY_ID: 'nationalCompanyId',
} as const;

export const PANEL_INDIVIDUAL_COMMITMENT_DETAIL_TABLE_COLUMNS: TableColumnType[] = [
  {
    label: 'شماره مشتری',
    accessor: PANEL_INDIVIDUAL_COMMITMENT_DETAIL_TABLE_COLUMNS_KEYS.CUSTOMER_NUMBER,
  },
  {
    label: 'نوع مشتری',
    accessor: PANEL_INDIVIDUAL_COMMITMENT_DETAIL_TABLE_COLUMNS_KEYS.CUSTOMER_TYPE,
  },
  {
    label: 'نام',
    accessor: PANEL_INDIVIDUAL_COMMITMENT_DETAIL_TABLE_COLUMNS_KEYS.FIRST_NAME,
  },
  {
    label: 'نام خانوادگی',
    accessor: PANEL_INDIVIDUAL_COMMITMENT_DETAIL_TABLE_COLUMNS_KEYS.LAST_NAME,
  },
  {
    label: 'کدملی/شناسه فراگیر اتباع',
    accessor: PANEL_INDIVIDUAL_COMMITMENT_DETAIL_TABLE_COLUMNS_KEYS.NATIONAL_ID,
  },
  {
    label: 'نام شرکت /موسسه',
    accessor: PANEL_INDIVIDUAL_COMMITMENT_DETAIL_TABLE_COLUMNS_KEYS.COMPANY_NAME,
  },
  {
    label: 'تاریخ برگشت چک',
    accessor: PANEL_INDIVIDUAL_COMMITMENT_DETAIL_TABLE_COLUMNS_KEYS.CHECK_RETURN_DATE,
  },
  {
    label: 'شناسه ملی',
    accessor: PANEL_INDIVIDUAL_COMMITMENT_DETAIL_TABLE_COLUMNS_KEYS.NATIONAL_COMPANY_ID,
  },
];

export const PANEL_INDIVIDUAL_COMMITMENT_DETAIL_TABLE_FAKE_DATA = [
  {
    id: 1,
    [PANEL_INDIVIDUAL_COMMITMENT_DETAIL_TABLE_COLUMNS_KEYS.CUSTOMER_NUMBER]: '10234567',
    [PANEL_INDIVIDUAL_COMMITMENT_DETAIL_TABLE_COLUMNS_KEYS.CUSTOMER_TYPE]: 'حقیقی',
    [PANEL_INDIVIDUAL_COMMITMENT_DETAIL_TABLE_COLUMNS_KEYS.FIRST_NAME]: 'علی',
    [PANEL_INDIVIDUAL_COMMITMENT_DETAIL_TABLE_COLUMNS_KEYS.LAST_NAME]: 'محمدی',
    [PANEL_INDIVIDUAL_COMMITMENT_DETAIL_TABLE_COLUMNS_KEYS.NATIONAL_ID]: '1234567890',
    [PANEL_INDIVIDUAL_COMMITMENT_DETAIL_TABLE_COLUMNS_KEYS.COMPANY_NAME]: '-',
    [PANEL_INDIVIDUAL_COMMITMENT_DETAIL_TABLE_COLUMNS_KEYS.CHECK_RETURN_DATE]: '-',
    [PANEL_INDIVIDUAL_COMMITMENT_DETAIL_TABLE_COLUMNS_KEYS.NATIONAL_COMPANY_ID]: '-',
  },
  {
    id: 2,
    [PANEL_INDIVIDUAL_COMMITMENT_DETAIL_TABLE_COLUMNS_KEYS.CUSTOMER_NUMBER]: '20876543',
    [PANEL_INDIVIDUAL_COMMITMENT_DETAIL_TABLE_COLUMNS_KEYS.CUSTOMER_TYPE]: 'حقوقی',
    [PANEL_INDIVIDUAL_COMMITMENT_DETAIL_TABLE_COLUMNS_KEYS.FIRST_NAME]: '-',
    [PANEL_INDIVIDUAL_COMMITMENT_DETAIL_TABLE_COLUMNS_KEYS.LAST_NAME]: '-',
    [PANEL_INDIVIDUAL_COMMITMENT_DETAIL_TABLE_COLUMNS_KEYS.NATIONAL_ID]: '-',
    [PANEL_INDIVIDUAL_COMMITMENT_DETAIL_TABLE_COLUMNS_KEYS.COMPANY_NAME]: 'شرکت توسعه فناوری',
    [PANEL_INDIVIDUAL_COMMITMENT_DETAIL_TABLE_COLUMNS_KEYS.CHECK_RETURN_DATE]: '1402/07/18',
    [PANEL_INDIVIDUAL_COMMITMENT_DETAIL_TABLE_COLUMNS_KEYS.NATIONAL_COMPANY_ID]: '14012345678',
  },
];
