import type {TableColumnType} from "../../../../../../../components/others/Table/TableExports.ts";

export const INDIVIDUAL_ACCOUNT_SPECIAL_INSTRUCTIONS_TABLE_COLUMNS_KEYS = {
  APPLY_DATE: 'applyDate',
  REMOVE_DATE: 'removeDate',
  REASON_CODE: 'reasonCode',
  REASON_DESCRIPTION: 'reasonDescription',
} as const;

export const INDIVIDUAL_ACCOUNT_SPECIAL_INSTRUCTIONS_TABLE_COLUMNS: TableColumnType[] = [
  {
    label: 'تاریخ اعمال دستورالعمل',
    accessor: INDIVIDUAL_ACCOUNT_SPECIAL_INSTRUCTIONS_TABLE_COLUMNS_KEYS.APPLY_DATE,
  },
  {
    label: 'تاریخ حذف دستورالعمل',
    accessor: INDIVIDUAL_ACCOUNT_SPECIAL_INSTRUCTIONS_TABLE_COLUMNS_KEYS.REMOVE_DATE,
  },
  {
    label: 'کد علت',
    accessor: INDIVIDUAL_ACCOUNT_SPECIAL_INSTRUCTIONS_TABLE_COLUMNS_KEYS.REASON_CODE,
  },
  {
    label: 'شرح علت',
    accessor: INDIVIDUAL_ACCOUNT_SPECIAL_INSTRUCTIONS_TABLE_COLUMNS_KEYS.REASON_DESCRIPTION,
  },
];

export const INDIVIDUAL_ACCOUNT_SPECIAL_INSTRUCTIONS_TABLE_FAKE_DATA = [
  {
    id: 1,
    [INDIVIDUAL_ACCOUNT_SPECIAL_INSTRUCTIONS_TABLE_COLUMNS_KEYS.APPLY_DATE]: '1403/01/10',
    [INDIVIDUAL_ACCOUNT_SPECIAL_INSTRUCTIONS_TABLE_COLUMNS_KEYS.REMOVE_DATE]: '1403/02/15',
    [INDIVIDUAL_ACCOUNT_SPECIAL_INSTRUCTIONS_TABLE_COLUMNS_KEYS.REASON_CODE]: '101',
    [INDIVIDUAL_ACCOUNT_SPECIAL_INSTRUCTIONS_TABLE_COLUMNS_KEYS.REASON_DESCRIPTION]: 'مسدودی حساب به درخواست مشتری',
  },
  {
    id: 2,
    [INDIVIDUAL_ACCOUNT_SPECIAL_INSTRUCTIONS_TABLE_COLUMNS_KEYS.APPLY_DATE]: '1402/11/05',
    [INDIVIDUAL_ACCOUNT_SPECIAL_INSTRUCTIONS_TABLE_COLUMNS_KEYS.REMOVE_DATE]: '-',
    [INDIVIDUAL_ACCOUNT_SPECIAL_INSTRUCTIONS_TABLE_COLUMNS_KEYS.REASON_CODE]: '205',
    [INDIVIDUAL_ACCOUNT_SPECIAL_INSTRUCTIONS_TABLE_COLUMNS_KEYS.REASON_DESCRIPTION]: 'محدودیت برداشت وجه',
  },
  {
    id: 3,
    [INDIVIDUAL_ACCOUNT_SPECIAL_INSTRUCTIONS_TABLE_COLUMNS_KEYS.APPLY_DATE]: '1403/03/01',
    [INDIVIDUAL_ACCOUNT_SPECIAL_INSTRUCTIONS_TABLE_COLUMNS_KEYS.REMOVE_DATE]: '1403/03/20',
    [INDIVIDUAL_ACCOUNT_SPECIAL_INSTRUCTIONS_TABLE_COLUMNS_KEYS.REASON_CODE]: '310',
    [INDIVIDUAL_ACCOUNT_SPECIAL_INSTRUCTIONS_TABLE_COLUMNS_KEYS.REASON_DESCRIPTION]: 'دستور قضایی',
  },
];
