import type {TableColumnType} from "../../../../components/others/Table/TableExports.ts";

export const PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS = {
  ANNUAL_DEPOSIT_MAX: 'annualDepositMax',
  ANNUAL_WITHDRAWAL_MAX: 'annualWithdrawalMax',
  PER_TRANSACTION_MAX: 'perTransactionMax',
  MAIN_INCOME_MAX: 'mainIncomeMax',
  TRANSACTION_ORIGIN_DEST: 'transactionOriginDest',
  ANNOUNCEMENT_DATE: 'announcementDate',
  FROM_DATE: 'fromDate',
  TO_DATE: 'toDate',
  REGISTRATION_DATE: 'registrationDate',
} as const;

export const PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS: TableColumnType[] = [
  {
    label: 'پیش بینی حداکثر مبلغ واریزی سالیانه',
    accessor: PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.ANNUAL_DEPOSIT_MAX,
  },
  {
    label: 'پیش بینی حداکثر مبلغ برداشت سالیانه',
    accessor: PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.ANNUAL_WITHDRAWAL_MAX,
  },
  {
    label: 'پیش بینی حداکثر مبلغ هر تراکنش',
    accessor: PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.PER_TRANSACTION_MAX,
  },
  {
    label: 'حداکثر مبلغ درآمد از کسب و کار اصلی',
    accessor: PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.MAIN_INCOME_MAX,
  },
  {
    label: 'انواع مبدا و مقصد مورد انتظار تراکنش',
    accessor: PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.TRANSACTION_ORIGIN_DEST,
  },
  {
    label: 'تاریخ اعلام',
    accessor: PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.ANNOUNCEMENT_DATE,
  },
  {
    label: 'از تاریخ',
    accessor: PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.FROM_DATE,
  },
  {
    label: 'تا تاریخ',
    accessor: PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.TO_DATE,
  },
  {
    label: 'تاریخ ثبت',
    accessor: PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.REGISTRATION_DATE,
  },
];

export const PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_FAKE_DATA = [
  {
    id: 1,
    [PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.ANNUAL_DEPOSIT_MAX]: '1200000',
    [PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.ANNUAL_WITHDRAWAL_MAX]: '600000',
    [PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.PER_TRANSACTION_MAX]: '250000',
    [PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.MAIN_INCOME_MAX]: '2000000',
    [PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.TRANSACTION_ORIGIN_DEST]: 'Salary; ClientPayment',
    [PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.ANNOUNCEMENT_DATE]: '2026-03-20',
    [PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.FROM_DATE]: '2026-01-01',
    [PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.TO_DATE]: '2026-12-31',
    [PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.REGISTRATION_DATE]: '2026-01-15',
  },
  {
    id: 2,
    [PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.ANNUAL_DEPOSIT_MAX]: '900000',
    [PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.ANNUAL_WITHDRAWAL_MAX]: '500000',
    [PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.PER_TRANSACTION_MAX]: '150000',
    [PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.MAIN_INCOME_MAX]: '1500000',
    [PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.TRANSACTION_ORIGIN_DEST]: 'OnlineSales; B2B',
    [PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.ANNOUNCEMENT_DATE]: '2026-02-01',
    [PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.FROM_DATE]: '2025-12-01',
    [PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.TO_DATE]: '2026-11-30',
    [PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.REGISTRATION_DATE]: '2026-02-18',
  },
  {
    id: 3,
    [PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.ANNUAL_DEPOSIT_MAX]: '2000000',
    [PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.ANNUAL_WITHDRAWAL_MAX]: '1000000',
    [PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.PER_TRANSACTION_MAX]: '300000',
    [PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.MAIN_INCOME_MAX]: '3000000',
    [PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.TRANSACTION_ORIGIN_DEST]: 'Invoices; Retail',
    [PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.ANNOUNCEMENT_DATE]: '2026-04-10',
    [PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.FROM_DATE]: '2026-01-01',
    [PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.TO_DATE]: '2026-12-31',
    [PANEL_ECONOMIC_PRIMARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.REGISTRATION_DATE]: '2026-04-01',
  },
];