import type {TableColumnType} from "../../../../../components/others/Table/TableExports.ts";
import TABLE_RENDER_TYPES from "../../../../../components/others/Table/constances/renderTypes.ts";
import Tag from "../../../../../components/others/Tag/Tag.tsx";


export const PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS = {
  FACILITY_NUMBER: 'facilityNumber',
  FACILITY_AMOUNT: 'facilityAmount',
  TOTAL_FACILITY_AMOUNT: 'totalFacilityAmount',
  INTEREST_RATE: 'interestRate',
  PAID_AMOUNT: 'paidAmount',
  REMAINING_AMOUNT: 'remainingAmount',
  STATUS: 'status',
  FACILITY_TYPE: 'facilityType',
  FACILITY_SUB_TYPE: 'facilitySubType',
  ALLOCATION_DATE: 'allocationDate',
  END_DATE: 'endDate',
  FACILITY_BRANCH_CODE: 'facilityBranchCode',
  FACILITY_BRANCH_NAME: 'facilityBranchName',
  FACILITY_REGION_CODE: 'facilityRegionCode',
  FACILITY_REGION_NAME: 'facilityRegionName',
} as const;

export const PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS: TableColumnType[] = [
  {
    label: 'شماره تسهیلات',
    accessor: PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_NUMBER,
  },
  {
    label: 'مبلغ تسهیلات',
    accessor: PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_AMOUNT,
  },
  {
    label: 'مبلغ کل تسهیلات',
    accessor: PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.TOTAL_FACILITY_AMOUNT,
  },
  {
    label: 'نرخ سود',
    accessor: PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.INTEREST_RATE,
  },
  {
    label: 'مبلغ پرداخت شده',
    accessor: PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.PAID_AMOUNT,
  },
  {
    label: 'مانده',
    accessor: PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.REMAINING_AMOUNT,
  },
  {
    label: 'وضعیت',
    accessor: PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.STATUS,
  },
  {
    label: 'نوع تسهیلات',
    accessor: PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_TYPE,
  },
  {
    label: 'زیرنوع تسهیلات',
    accessor: PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_SUB_TYPE,
  },
  {
    label: 'تاریخ تخصیص',
    accessor: PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.ALLOCATION_DATE,
  },
  {
    label: 'تاریخ پایان',
    accessor: PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.END_DATE,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN,
  },
  {
    label: 'کدشعبه تسهیلات',
    accessor: PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_BRANCH_CODE,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN,
  },
  {
    label: 'نام شعبه',
    accessor: PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_BRANCH_NAME,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN,
  },
  {
    label: 'کد منطقه تسهیلات',
    accessor: PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_REGION_CODE,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN,
  },
  {
    label: 'نام منطقه',
    accessor: PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_REGION_NAME,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN,
  },
];

export const PANEL_INDIVIDUAL_FACILITIES_TABLE_FAKE_DATA = [
  {

  },
  {
    id: 2,
    [PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_NUMBER]: 'FAC-1403002',
    [PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_AMOUNT]: '2,000,000,000 ریال',
    [PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.TOTAL_FACILITY_AMOUNT]: '2,450,000,000 ریال',
    [PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.INTEREST_RATE]: '12%',
    [PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.PAID_AMOUNT]: '2,450,000,000 ریال',
    [PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.REMAINING_AMOUNT]: '0 ریال',
    [PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.STATUS]: (
      <Tag text='تسویه شده' color='blue' variant='fade'/>
    ),
    [PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_TYPE]: 'قرض الحسنه',
    [PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_SUB_TYPE]: 'ازدواج',
    [PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.ALLOCATION_DATE]: '1399/08/01',
    [PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.END_DATE]: '1403/08/01',
    [PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_BRANCH_CODE]: '2045',
    [PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_BRANCH_NAME]: 'شعبه انقلاب',
    [PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_REGION_CODE]: '20',
    [PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_REGION_NAME]: 'منطقه غرب',
  },
];
