import type {TableColumnType} from "../../../../../../../components/others/Table/TableExports.ts";


export const INDIVIDUAL_ACCOUNT_RETURNED_CHEQUES_TABLE_COLUMNS_KEYS = {
  CHECK_NUMBER: 'checkNumber',
  CHECK_AMOUNT: 'checkAmount',
  CHECK_DATE: 'checkDate',
  RETURN_DATE: 'returnDate',
  CLEARANCE_DATE: 'clearanceDate',
} as const;

export const INDIVIDUAL_ACCOUNT_RETURNED_CHEQUES_TABLE_COLUMNS: TableColumnType[] = [
  {
    label: 'شماره چک',
    accessor: INDIVIDUAL_ACCOUNT_RETURNED_CHEQUES_TABLE_COLUMNS_KEYS.CHECK_NUMBER,
  },
  {
    label: 'مبلغ چک',
    accessor: INDIVIDUAL_ACCOUNT_RETURNED_CHEQUES_TABLE_COLUMNS_KEYS.CHECK_AMOUNT,
  },
  {
    label: 'تاریخ چک',
    accessor: INDIVIDUAL_ACCOUNT_RETURNED_CHEQUES_TABLE_COLUMNS_KEYS.CHECK_DATE,
  },
  {
    label: 'تاریخ برگشت چک',
    accessor: INDIVIDUAL_ACCOUNT_RETURNED_CHEQUES_TABLE_COLUMNS_KEYS.RETURN_DATE,
  },
  {
    label: 'تاریخ رفع سوء اثر',
    accessor: INDIVIDUAL_ACCOUNT_RETURNED_CHEQUES_TABLE_COLUMNS_KEYS.CLEARANCE_DATE,
  },
];

export const INDIVIDUAL_ACCOUNT_RETURNED_CHEQUES_TABLE_FAKE_DATA = [
  {
    id: 1,
    [INDIVIDUAL_ACCOUNT_RETURNED_CHEQUES_TABLE_COLUMNS_KEYS.CHECK_NUMBER]: '548796',
    [INDIVIDUAL_ACCOUNT_RETURNED_CHEQUES_TABLE_COLUMNS_KEYS.CHECK_AMOUNT]: '250,000,000 ریال',
    [INDIVIDUAL_ACCOUNT_RETURNED_CHEQUES_TABLE_COLUMNS_KEYS.CHECK_DATE]: '1403/01/15',
    [INDIVIDUAL_ACCOUNT_RETURNED_CHEQUES_TABLE_COLUMNS_KEYS.RETURN_DATE]: '1403/01/20',
    [INDIVIDUAL_ACCOUNT_RETURNED_CHEQUES_TABLE_COLUMNS_KEYS.CLEARANCE_DATE]: '1403/02/05',
  },
  {
    id: 2,
    [INDIVIDUAL_ACCOUNT_RETURNED_CHEQUES_TABLE_COLUMNS_KEYS.CHECK_NUMBER]: '874125',
    [INDIVIDUAL_ACCOUNT_RETURNED_CHEQUES_TABLE_COLUMNS_KEYS.CHECK_AMOUNT]: '480,000,000 ریال',
    [INDIVIDUAL_ACCOUNT_RETURNED_CHEQUES_TABLE_COLUMNS_KEYS.CHECK_DATE]: '1402/11/08',
    [INDIVIDUAL_ACCOUNT_RETURNED_CHEQUES_TABLE_COLUMNS_KEYS.RETURN_DATE]: '1402/11/15',
    [INDIVIDUAL_ACCOUNT_RETURNED_CHEQUES_TABLE_COLUMNS_KEYS.CLEARANCE_DATE]: '1402/12/01',
  },
  {
    id: 3,
    [INDIVIDUAL_ACCOUNT_RETURNED_CHEQUES_TABLE_COLUMNS_KEYS.CHECK_NUMBER]: '963258',
    [INDIVIDUAL_ACCOUNT_RETURNED_CHEQUES_TABLE_COLUMNS_KEYS.CHECK_AMOUNT]: '120,000,000 ریال',
    [INDIVIDUAL_ACCOUNT_RETURNED_CHEQUES_TABLE_COLUMNS_KEYS.CHECK_DATE]: '1403/03/10',
    [INDIVIDUAL_ACCOUNT_RETURNED_CHEQUES_TABLE_COLUMNS_KEYS.RETURN_DATE]: '1403/03/14',
    [INDIVIDUAL_ACCOUNT_RETURNED_CHEQUES_TABLE_COLUMNS_KEYS.CLEARANCE_DATE]: '-',
  },
];
