import type {TableColumnType} from "../../../../../../../components/others/Table/TableExports.ts";

export const PANEL_TRANSACTION_HISTORY_E_SERVICE_PERIOD_DETAIL_TABLE_COLUMNS_KEYS = {
  OPERATION_TYPE: 'operationType',
  CREDITOR_AMOUNT: 'creditorAmount',
  DEBTOR_AMOUNT: 'debtorAmount',
  BALANCE: 'balance',
  DATE: 'date',
} as const;

export const PANEL_TRANSACTION_HISTORY_E_SERVICE_PERIOD_DETAIL_TABLE_COLUMNS: TableColumnType[] = [
  {
    label: 'نوع عملیات',
    accessor: PANEL_TRANSACTION_HISTORY_E_SERVICE_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.OPERATION_TYPE,
  },
  {
    label: 'بستانکار',
    accessor: PANEL_TRANSACTION_HISTORY_E_SERVICE_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.CREDITOR_AMOUNT,
  },
  {
    label: 'بدهکار',
    accessor: PANEL_TRANSACTION_HISTORY_E_SERVICE_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.DEBTOR_AMOUNT,
  },
  {
    label: 'بستانکار - بدهکار',
    accessor: PANEL_TRANSACTION_HISTORY_E_SERVICE_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.BALANCE,
  },
  {
    label: 'تاریخ',
    accessor: PANEL_TRANSACTION_HISTORY_E_SERVICE_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.DATE,
  },
];

export const PANEL_TRANSACTION_HISTORY_E_SERVICE_PERIOD_DETAIL_TABLE_FAKE_DATA = [
  {
    id: 1,
    [PANEL_TRANSACTION_HISTORY_E_SERVICE_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.OPERATION_TYPE]: 'واریز',
    [PANEL_TRANSACTION_HISTORY_E_SERVICE_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.CREDITOR_AMOUNT]: '850,000,000',
    [PANEL_TRANSACTION_HISTORY_E_SERVICE_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.DEBTOR_AMOUNT]: '120,000,000',
    [PANEL_TRANSACTION_HISTORY_E_SERVICE_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.BALANCE]: '730,000,000',
    [PANEL_TRANSACTION_HISTORY_E_SERVICE_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.DATE]: '1405/02/02',
  },
  {
    id: 2,
    [PANEL_TRANSACTION_HISTORY_E_SERVICE_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.OPERATION_TYPE]: 'برداشت',
    [PANEL_TRANSACTION_HISTORY_E_SERVICE_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.CREDITOR_AMOUNT]: '300,000,000',
    [PANEL_TRANSACTION_HISTORY_E_SERVICE_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.DEBTOR_AMOUNT]: '450,000,000',
    [PANEL_TRANSACTION_HISTORY_E_SERVICE_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.BALANCE]: '-150,000,000',
    [PANEL_TRANSACTION_HISTORY_E_SERVICE_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.DATE]: '1405/02/02',
  },
];
