import type { TableColumnType } from "../../../../components/others/Table/TableExports.ts";


export const PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS = {
  COMPANY_TYPE: 'companyType',
  ACTIVITY_TYPE_OR_FIELD: 'activityTypeOrField',
  ACTIVITY_CLASSIFICATION: 'activityClassification',
  ECONOMIC_CODE: 'economicCode',
  COMMERCIAL_CARD_NUMBER: 'commercialCardNumber',
  DECLARATION_DATE: 'declarationDate',
  FROM_DATE: 'fromDate',
  REGISTRATION_DATE: 'registrationDate',
} as const;


export const PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS: TableColumnType[] = [
  {
    label: 'نوع شرکت',
    accessor: PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.COMPANY_TYPE,
  },
  {
    label: 'نوع فعالیت / حوزه کاری',
    accessor:
    PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.ACTIVITY_TYPE_OR_FIELD,
  },
  {
    label: 'طبقه‌بندی فعالیت',
    accessor: PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.ACTIVITY_CLASSIFICATION,
  },
  {
    label: 'کد اقتصادی',
    accessor: PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.ECONOMIC_CODE,
  },
  {
    label: 'شماره کارت بازرگانی',
    accessor: PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.COMMERCIAL_CARD_NUMBER,
  },
  {
    label: 'تاریخ اعلام',
    accessor: PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.DECLARATION_DATE,
  },
  {
    label: 'از تاریخ',
    accessor: PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.FROM_DATE,
  },
  {
    label: 'تاریخ ثبت',
    accessor: PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.REGISTRATION_DATE,
  },
];

export const PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_FAKE_DATA = [
  {
    id: 1,
    [PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.COMPANY_TYPE]:
      'سهامی خاص',
    [PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.ACTIVITY_TYPE_OR_FIELD]:
      'تولید تجهیزات الکترونیکی',
    [PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.ACTIVITY_CLASSIFICATION]:
      'صنعتی',
    [PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.ECONOMIC_CODE]:
      '41126359879',
    [PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.COMMERCIAL_CARD_NUMBER]:
      'MC-112233',
    [PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.DECLARATION_DATE]:
      '2026-02-01',
    [PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.FROM_DATE]:
      '2026-01-15',
    [PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.REGISTRATION_DATE]:
      '2026-02-20',
  },
  {
    id: 2,
    [PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.COMPANY_TYPE]:
      'مسئولیت محدود',
    [PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.ACTIVITY_TYPE_OR_FIELD]:
      'خدمات مشاوره مالی',
    [PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.ACTIVITY_CLASSIFICATION]:
      'خدماتی',
    [PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.ECONOMIC_CODE]:
      '51276439021',
    [PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.COMMERCIAL_CARD_NUMBER]:
      'MC-223344',
    [PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.DECLARATION_DATE]:
      '2026-03-10',
    [PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.FROM_DATE]:
      '2026-03-01',
    [PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.REGISTRATION_DATE]:
      '2026-03-18',
  },
  {
    id: 3,
    [PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.COMPANY_TYPE]:
      'تعاونی تولیدی',
    [PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.ACTIVITY_TYPE_OR_FIELD]:
      'پرورش طیور',
    [PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.ACTIVITY_CLASSIFICATION]:
      'کشاورزی',
    [PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.ECONOMIC_CODE]:
      '78123940213',
    [PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.COMMERCIAL_CARD_NUMBER]:
      'MC-334455',
    [PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.DECLARATION_DATE]:
      '2025-11-25',
    [PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.FROM_DATE]:
      '2025-11-01',
    [PANEL_ECONOMIC_ACTIVITY_LEGAL_INFORMATION_TABLE_COLUMNS_KEYS.REGISTRATION_DATE]:
      '2025-12-10',
  },
];
