import TABLE_RENDER_TYPES from "../../../../components/others/Table/constances/renderTypes.ts";
import type {TableColumnType} from "../../../../components/others/Table/TableExports.ts";

export const PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS = {
  EMPLOYMENT_STATUS_SUBTYPE: 'employmentStatusSubType',
  EMPLOYMENT_STATUS: 'employmentStatus',
  JOB_CODE: 'jobCode',
  JOB_TITLE: 'jobTitle',
  OCCUPATIONAL_ACTIVITY_CODE: 'occupationalActivityCode',
  OCCUPATIONAL_ACTIVITY_TITLE: 'occupationalActivityTitle',
  EMPLOYMENT_START_DATE: 'employmentStartDate',
  INSURANCE_TYPE: 'insuranceType',
  EMPLOYER_TYPE: 'employerType',
  EMPLOYER_ID: 'employerId',
  REGISTRATION_DATE: 'registrationDate',
  EMPLOYER_NAME: 'employerName',
  EMPLOYER_INDUSTRY_CODE: 'employerIndustryCode',
  EMPLOYER_INDUSTRY_TITLE: 'employerIndustryTitle',
  ECONOMIC_CODE: 'economicCode',
  COMMERCIAL_CARD_ID: 'commercialCardID',
  BUSINESS_LICENSE: 'businessLicense',
  LICENSE_NUMBER: 'licenseNumber',
  ISSUING_AUTHORITY: 'issuingAuthority',
  LICENSE_ISSUE_DATE: 'licenseIssueDate',
  LICENSE_EXPIRATION_ISSUE_DATE: 'licenseExpirationIssueDate',
  DECLARATION_DATE: 'declarationDate',
  FROM_DATE: 'fromDate',
} as const;

export const PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS: TableColumnType[] = [
  {
    label: 'زیر نوع وضعیت اشتغال',
    accessor: PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYMENT_STATUS_SUBTYPE,
  },
  {
    label: 'وضعیت اشتغال',
    accessor: PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYMENT_STATUS,
  },
  {
    label: 'کد شغل',
    accessor: PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.JOB_CODE,
  },
  {
    label: 'عنوان شغل',
    accessor: PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.JOB_TITLE,
  },
  {
    label: 'کد فعالیت شغلی',
    accessor: PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.OCCUPATIONAL_ACTIVITY_CODE,
  },
  {
    label: 'عنوان فعالیت شغلی',
    accessor: PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.OCCUPATIONAL_ACTIVITY_TITLE,
  },
  {
    label: 'تاریخ شروع به کار',
    accessor: PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYMENT_START_DATE,
  },
  {
    label: 'نوع بیمه',
    accessor: PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.INSURANCE_TYPE,
  },
  {
    label: 'نوع کارفرما',
    accessor: PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_TYPE,
  },
  {
    label: 'شناسه کارفرما',
    accessor: PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_ID,
  },
  {
    label: 'تاریخ ثبت',
    accessor: PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.REGISTRATION_DATE,
  },
  {
    label: 'نام کارفرما',
    accessor: PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_NAME,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
  {
    label: 'کد حوزه کاری کارفرما',
    accessor: PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_INDUSTRY_CODE,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
  {
    label: 'عنوان حوزه کاری کارفرما',
    accessor: PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_INDUSTRY_TITLE,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
  {
    label: 'کد اقتصادی',
    accessor: PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.ECONOMIC_CODE,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
  {
    label: 'شناسه کارت بازرگانی',
    accessor: PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.COMMERCIAL_CARD_ID,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
  {
    label: 'مجوز/پروانه کسب و کار',
    accessor: PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.BUSINESS_LICENSE,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
  {
    label: 'شماره مجوز فعالیت',
    accessor: PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.LICENSE_NUMBER,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
  {
    label: 'مرجع صادرکننده مجوز',
    accessor: PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.ISSUING_AUTHORITY,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
  {
    label: 'تاریخ صدور مجوز',
    accessor: PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.LICENSE_ISSUE_DATE,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
  {
    label: 'تاریخ انقضاء مجوز',
    accessor: PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.LICENSE_EXPIRATION_ISSUE_DATE,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
  {
    label: 'تاریخ اعلام',
    accessor: PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.DECLARATION_DATE,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
  {
    label: 'از تاریخ',
    accessor: PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.FROM_DATE,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
];


export const PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_FAKE_DATA = [
  {
    id: 1,
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYMENT_STATUS_SUBTYPE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYMENT_STATUS]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.JOB_CODE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.JOB_TITLE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.OCCUPATIONAL_ACTIVITY_CODE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.OCCUPATIONAL_ACTIVITY_TITLE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYMENT_START_DATE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.INSURANCE_TYPE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_TYPE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_ID]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.REGISTRATION_DATE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_NAME]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_INDUSTRY_CODE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_INDUSTRY_TITLE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.ECONOMIC_CODE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.BUSINESS_LICENSE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.LICENSE_NUMBER]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.ISSUING_AUTHORITY]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.LICENSE_ISSUE_DATE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.LICENSE_EXPIRATION_ISSUE_DATE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.DECLARATION_DATE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.FROM_DATE]: '1234567890',
  },
  {
    id: 2,
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYMENT_STATUS_SUBTYPE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYMENT_STATUS]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.JOB_CODE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.JOB_TITLE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.OCCUPATIONAL_ACTIVITY_CODE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.OCCUPATIONAL_ACTIVITY_TITLE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYMENT_START_DATE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.INSURANCE_TYPE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_TYPE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_ID]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.REGISTRATION_DATE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_NAME]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_INDUSTRY_CODE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_INDUSTRY_TITLE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.ECONOMIC_CODE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.BUSINESS_LICENSE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.LICENSE_NUMBER]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.ISSUING_AUTHORITY]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.LICENSE_ISSUE_DATE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.LICENSE_EXPIRATION_ISSUE_DATE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.DECLARATION_DATE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.FROM_DATE]: '1234567890',
  },
  {
    id: 3,
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYMENT_STATUS_SUBTYPE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYMENT_STATUS]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.JOB_CODE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.JOB_TITLE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.OCCUPATIONAL_ACTIVITY_CODE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.OCCUPATIONAL_ACTIVITY_TITLE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYMENT_START_DATE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.INSURANCE_TYPE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_TYPE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_ID]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.REGISTRATION_DATE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_NAME]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_INDUSTRY_CODE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_INDUSTRY_TITLE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.ECONOMIC_CODE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.BUSINESS_LICENSE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.LICENSE_NUMBER]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.ISSUING_AUTHORITY]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.LICENSE_ISSUE_DATE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.LICENSE_EXPIRATION_ISSUE_DATE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.DECLARATION_DATE]: '1234567890',
    [PANEL_ECONOMIC_ACTIVITY_INFORMATION_TABLE_COLUMNS_KEYS.FROM_DATE]: '1234567890',
  },
]