import type {TableColumnType} from "../../../../../../components/others/Table/TableExports.ts";
import Tag from "../../../../../../components/others/Tag/Tag.tsx";
import ACTIONS_COLUMN from "../../../../../../components/others/Table/constances/actions/actionsColumn.ts";

export const PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS = {
  BRANCH_CODE: 'branchCode',
  BRANCH_NAME: 'branchName',
  REGION_CODE: 'regionCode',
  REGION_NAME: 'regionName',
  VISIT_COUNT: 'visitCount',
  TOTAL_CREDITOR: 'totalCreditor',
  TOTAL_DEBTOR: 'totalDebtor',
  BALANCE: 'balance',
  BRANCH_RISK: 'branchRisk',
} as const;

export const PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS: TableColumnType[] = [
  {
    label: 'کد شعبه',
    accessor: PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.BRANCH_CODE,
  },
  {
    label: 'نام شعبه',
    accessor: PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.BRANCH_NAME,
  },
  {
    label: 'کد منطقه',
    accessor: PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.REGION_CODE,
  },
  {
    label: 'نام منطقه',
    accessor: PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.REGION_NAME,
  },
  {
    label: 'تعداد مراجعه',
    accessor: PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.VISIT_COUNT,
  },
  {
    label: 'مجموع بستانکار',
    accessor: PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.TOTAL_CREDITOR,
  },
  {
    label: 'مجموع بدهکار',
    accessor: PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.TOTAL_DEBTOR,
  },
  {
    label: 'مجموع بستانکار - مجموع بدهکار',
    accessor: PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.BALANCE,
  },
  {
    label: 'ریسک شعبه',
    accessor: PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.BRANCH_RISK,
  },
  ACTIONS_COLUMN
];

export const PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_FAKE_DATA = [
  {
    id: 1,
    [PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.BRANCH_CODE]: '1021',
    [PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.BRANCH_NAME]: 'مرکزی',
    [PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.REGION_CODE]: '10',
    [PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.REGION_NAME]: 'تهران مرکزی',
    [PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.VISIT_COUNT]: 18,
    [PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.TOTAL_CREDITOR]: '1,250,000,000',
    [PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.TOTAL_DEBTOR]: '850,000,000',
    [PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.BALANCE]: '400,000,000',
    [PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.BRANCH_RISK]: (
      <Tag text='کم' color='green' variant='fade' />
    ),
  },
  {
    id: 2,
    [PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.BRANCH_CODE]: '2045',
    [PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.BRANCH_NAME]: 'ولیعصر',
    [PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.REGION_CODE]: '20',
    [PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.REGION_NAME]: 'تهران غرب',
    [PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.VISIT_COUNT]: 9,
    [PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.TOTAL_CREDITOR]: '420,000,000',
    [PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.TOTAL_DEBTOR]: '730,000,000',
    [PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.BALANCE]: '-310,000,000',
    [PANEL_TRANSACTION_HISTORY_BY_PERIOD_DETAIL_TABLE_COLUMNS_KEYS.BRANCH_RISK]: (
      <Tag text='زیاد' color='red' variant='fade' />
    ),
  },
];
