import type {TableColumnType} from "../../../../../components/others/Table/TableExports.ts";
import Tag from "../../../../../components/others/Tag/Tag.tsx";
import {
  PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS,
  PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS
} from "../../individual/facilities/index.constances.tsx";


export const PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS = {
  SHARED_CUSTOMER_NUMBER: 'sharedCustomerNumber',
  ...PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS_KEYS,
} as const;

export const PANEL_JOINT_FACILITIES_TABLE_COLUMNS: TableColumnType[] = [
  {
    label: 'شماره مشتری مشترک',
    accessor: PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.SHARED_CUSTOMER_NUMBER,
  },
  ...PANEL_INDIVIDUAL_FACILITIES_TABLE_COLUMNS,
];

export const PANEL_JOINT_FACILITIES_TABLE_FAKE_DATA = [
  {
    id: 1,
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.SHARED_CUSTOMER_NUMBER]: '0103456789001',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_NUMBER]: 'FAC-1403001',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_AMOUNT]: '5,000,000,000 ریال',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.TOTAL_FACILITY_AMOUNT]: '6,200,000,000 ریال',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.INTEREST_RATE]: '18%',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.PAID_AMOUNT]: '2,500,000,000 ریال',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.REMAINING_AMOUNT]: '3,700,000,000 ریال',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.STATUS]: (
      <Tag text='فعال' color='green' variant='fade'/>
    ),
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_TYPE]: 'مرابحه',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_SUB_TYPE]: 'خرید کالا',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.ALLOCATION_DATE]: '1402/03/15',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.END_DATE]: '1406/03/15',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_BRANCH_CODE]: '1021',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_BRANCH_NAME]: 'شعبه ولیعصر',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_REGION_CODE]: '10',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_REGION_NAME]: 'منطقه مرکزی',
  },
  {
    id: 2,
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.SHARED_CUSTOMER_NUMBER]: '0103456789001',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_NUMBER]: 'FAC-1403002',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_AMOUNT]: '2,000,000,000 ریال',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.TOTAL_FACILITY_AMOUNT]: '2,450,000,000 ریال',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.INTEREST_RATE]: '12%',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.PAID_AMOUNT]: '2,450,000,000 ریال',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.REMAINING_AMOUNT]: '0 ریال',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.STATUS]: (
      <Tag text='تسویه شده' color='blue' variant='fade'/>
    ),
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_TYPE]: 'قرض الحسنه',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_SUB_TYPE]: 'ازدواج',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.ALLOCATION_DATE]: '1399/08/01',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.END_DATE]: '1403/08/01',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_BRANCH_CODE]: '2045',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_BRANCH_NAME]: 'شعبه انقلاب',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_REGION_CODE]: '20',
    [PANEL_JOINT_FACILITIES_TABLE_COLUMNS_KEYS.FACILITY_REGION_NAME]: 'منطقه غرب',
  },
];
