import type {TableColumnType} from "../../../../../components/others/Table/TableExports.ts";
import Tag from "../../../../../components/others/Tag/Tag.tsx";
import {
  PANEL_INDIVIDUAL_E_SERVICE_PORTAL_TABLE_COLUMNS,
  PANEL_INDIVIDUAL_E_SERVICE_PORTAL_TABLE_COLUMNS_KEYS
} from "../../individual/eServicePortal/index.constances.tsx";


export const PANEL_JOINT_E_SERVICE_PORTAL_TABLE_COLUMNS_KEYS = {
  SHARED_CUSTOMER_NUMBER: 'sharedCustomerNumber',
...PANEL_INDIVIDUAL_E_SERVICE_PORTAL_TABLE_COLUMNS_KEYS,
} as const;

export const PANEL_JOINT_E_SERVICE_PORTAL_TABLE_COLUMNS: TableColumnType[] = [
  {
    label: 'شماره مشتری مشترک',
    accessor: PANEL_JOINT_E_SERVICE_PORTAL_TABLE_COLUMNS_KEYS.SHARED_CUSTOMER_NUMBER,
  },
  ...PANEL_INDIVIDUAL_E_SERVICE_PORTAL_TABLE_COLUMNS
];

export const PANEL_JOINT_E_SERVICE_PORTAL_TABLE_FAKE_DATA = [
  {
    id: 1,
    [PANEL_JOINT_E_SERVICE_PORTAL_TABLE_COLUMNS_KEYS.SHARED_CUSTOMER_NUMBER]: '0103456789001',
    [PANEL_JOINT_E_SERVICE_PORTAL_TABLE_COLUMNS_KEYS.E_SERVICE_PORTAL]: 'اینترنت بانک',
    [PANEL_JOINT_E_SERVICE_PORTAL_TABLE_COLUMNS_KEYS.ACTIVATION_DATE]: '1401/03/15',
    [PANEL_JOINT_E_SERVICE_PORTAL_TABLE_COLUMNS_KEYS.STATUS]: (
      <Tag text='فعال' color='green' variant='fade'/>
    ),
    [PANEL_JOINT_E_SERVICE_PORTAL_TABLE_COLUMNS_KEYS.LAST_ACTIVITY_DATE]: '1403/02/10',
    [PANEL_JOINT_E_SERVICE_PORTAL_TABLE_COLUMNS_KEYS.DEACTIVATION_DATE]: '-',
  },
  {
    id: 2,
    [PANEL_JOINT_E_SERVICE_PORTAL_TABLE_COLUMNS_KEYS.SHARED_CUSTOMER_NUMBER]: '0103456789001',
    [PANEL_JOINT_E_SERVICE_PORTAL_TABLE_COLUMNS_KEYS.E_SERVICE_PORTAL]: 'موبایل بانک',
    [PANEL_JOINT_E_SERVICE_PORTAL_TABLE_COLUMNS_KEYS.ACTIVATION_DATE]: '1400/08/01',
    [PANEL_JOINT_E_SERVICE_PORTAL_TABLE_COLUMNS_KEYS.STATUS]: (
      <Tag text='غیرفعال' color='red' variant='fade'/>
    ),
    [PANEL_JOINT_E_SERVICE_PORTAL_TABLE_COLUMNS_KEYS.LAST_ACTIVITY_DATE]: '1402/11/22',
    [PANEL_JOINT_E_SERVICE_PORTAL_TABLE_COLUMNS_KEYS.DEACTIVATION_DATE]: '1403/01/05',
  },
];
