import type {TabsProps} from "../../../components/others/Tab/Tab.tsx";
import type {TableColumnType} from "../../../components/others/Table/TableExports.ts";
import TABLE_RENDER_TYPES from "../../../components/others/Table/constances/renderTypes.ts";


export const PANEL_ECONOMIC_INFORMATION_PAGE_TABS_KEYS = {
  ECONOMIC_ACTIVITY: 'economicActivity',
  PRIMARY_SOURCE_OF_INCOME: 'primarySourceOfIncome',
  SECONDARY_SOURCE_OF_INCOME: 'secondarySourceOfIncome',
}

export const PANEL_ECONOMIC_INFORMATION_PAGE_TABS: TabsProps['tabs'] = [
  {
    id: PANEL_ECONOMIC_INFORMATION_PAGE_TABS_KEYS.ECONOMIC_ACTIVITY,
    title: 'اطلاعات فعالیت اقتصادی'
  },
  {
    id: PANEL_ECONOMIC_INFORMATION_PAGE_TABS_KEYS.PRIMARY_SOURCE_OF_INCOME,
    title: 'اطلاعات منبع درآمد اصلی'
  },
  {
    id: PANEL_ECONOMIC_INFORMATION_PAGE_TABS_KEYS.SECONDARY_SOURCE_OF_INCOME,
    title: 'اطلاعات منابع درآمدی ثانویه'
  },
]

export const PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS = {
  EMPLOYMENT_STATUS_SUBTYPE: 'employmentStatusSubType',
  EMPLOYMENT_STATUS: 'employmentStatus',
  JOB_CODE: 'jobCode',
  JOB_TITLE: 'jobTitle',
  OCCUPATIONAL_ACTIVITY_CODE: 'occupationalActivityCode',
  OCCUPATIONAL_ACTIVITY_TITLE: 'occupationalActivityTitle',
  EMPLOYMENT_START_DATE: 'employmentStartDate',
  INSURANCE_TYPE: 'insuranceType',
  EMPLOYER_TYPE: 'employerType',
  EMPLOYER_ID: 'employerId',
  REGISTRATION_DATE: 'registrationDate',
  EMPLOYER_NAME: 'employerName',
  EMPLOYER_INDUSTRY_CODE: 'employerIndustryCode',
  EMPLOYER_INDUSTRY_TITLE: 'employerIndustryTitle',
  ECONOMIC_CODE: 'economicCode',
  BUSINESS_LICENSE: 'businessLicense',
  LICENSE_NUMBER: 'licenseNumber',
  ISSUING_AUTHORITY: 'issuingAuthority',
  LICENSE_ISSUE_DATE: 'licenseIssueDate',
  DECLARATION_DATE: 'declarationDate',
  FROM_DATE: 'fromDate',
} as const;

export const PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS: TableColumnType[] = [
  {
    label: 'زیر نوع وضعیت اشتغال',
    accessor: PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYMENT_STATUS_SUBTYPE,
  },
  {
    label: 'وضعیت اشتغال',
    accessor: PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYMENT_STATUS,
  },
  {
    label: 'کد شغل',
    accessor: PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.JOB_CODE,
  },
  {
    label: 'عنوان شغل',
    accessor: PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.JOB_TITLE,
  },
  {
    label: 'کد فعالیت شغلی',
    accessor: PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.OCCUPATIONAL_ACTIVITY_CODE,
  },
  {
    label: 'عنوان فعالیت شغلی',
    accessor: PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.OCCUPATIONAL_ACTIVITY_TITLE,
  },
  {
    label: 'تاریخ شروع به کار',
    accessor: PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYMENT_START_DATE,
  },
  {
    label: 'نوع بیمه',
    accessor: PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.INSURANCE_TYPE,
  },
  {
    label: 'نوع کارفرما',
    accessor: PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_TYPE,
  },
  {
    label: 'شناسه کارفرما',
    accessor: PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_ID,
  },
  {
    label: 'تاریخ ثبت',
    accessor: PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.REGISTRATION_DATE,
  },
  {
    label: 'نام کارفرما',
    accessor: PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_NAME,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
  {
    label: 'کد حوزه کاری کارفرما',
    accessor: PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_INDUSTRY_CODE,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
  {
    label: 'عنوان حوزه کاری کارفرما',
    accessor: PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_INDUSTRY_TITLE,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
  {
    label: 'کد اقتصادی',
    accessor: PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.ECONOMIC_CODE,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
  {
    label: 'مجوز/پروانه کسب و کار',
    accessor: PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.BUSINESS_LICENSE,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
  {
    label: 'شماره مجوز فعالیت',
    accessor: PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.LICENSE_NUMBER,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
  {
    label: 'مرجع صادرکننده مجوز',
    accessor: PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.ISSUING_AUTHORITY,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
  {
    label: 'تاریخ صدور مجوز',
    accessor: PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.LICENSE_ISSUE_DATE,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
  {
    label: 'تاریخ اعلام',
    accessor: PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.DECLARATION_DATE,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
  {
    label: 'از تاریخ',
    accessor: PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.FROM_DATE,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
];


export const PANEL_ECONOMIC_INFORMATION_TABLE_FAKE_DATA = [
  {
    id: 1,
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYMENT_STATUS_SUBTYPE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYMENT_STATUS]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.JOB_CODE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.JOB_TITLE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.OCCUPATIONAL_ACTIVITY_CODE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.OCCUPATIONAL_ACTIVITY_TITLE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYMENT_START_DATE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.INSURANCE_TYPE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_TYPE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_ID]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.REGISTRATION_DATE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_NAME]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_INDUSTRY_CODE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_INDUSTRY_TITLE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.ECONOMIC_CODE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.BUSINESS_LICENSE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.LICENSE_NUMBER]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.ISSUING_AUTHORITY]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.LICENSE_ISSUE_DATE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.DECLARATION_DATE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.FROM_DATE]: '',
  },
  {
    id: 2,
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYMENT_STATUS_SUBTYPE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYMENT_STATUS]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.JOB_CODE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.JOB_TITLE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.OCCUPATIONAL_ACTIVITY_CODE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.OCCUPATIONAL_ACTIVITY_TITLE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYMENT_START_DATE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.INSURANCE_TYPE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_TYPE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_ID]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.REGISTRATION_DATE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_NAME]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_INDUSTRY_CODE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_INDUSTRY_TITLE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.ECONOMIC_CODE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.BUSINESS_LICENSE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.LICENSE_NUMBER]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.ISSUING_AUTHORITY]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.LICENSE_ISSUE_DATE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.DECLARATION_DATE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.FROM_DATE]: '',
  },
  {
    id: 3,
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYMENT_STATUS_SUBTYPE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYMENT_STATUS]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.JOB_CODE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.JOB_TITLE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.OCCUPATIONAL_ACTIVITY_CODE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.OCCUPATIONAL_ACTIVITY_TITLE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYMENT_START_DATE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.INSURANCE_TYPE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_TYPE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_ID]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.REGISTRATION_DATE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_NAME]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_INDUSTRY_CODE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.EMPLOYER_INDUSTRY_TITLE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.ECONOMIC_CODE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.BUSINESS_LICENSE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.LICENSE_NUMBER]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.ISSUING_AUTHORITY]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.LICENSE_ISSUE_DATE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.DECLARATION_DATE]: '',
    [PANEL_ECONOMIC_INFORMATION_TABLE_COLUMNS_KEYS.FROM_DATE]: '',
  },
]