
const PANEL = '/panel'
const COMPREHENSIVE_INFO = `${PANEL}/comprehensive-info`

const BANKING_INFO = `${PANEL}/banking-info`
const PANEL_INDIVIDUAL_BANKING_INFORMATION = `${BANKING_INFO}/individual`
const PANEL_INDIVIDUAL_BANKING_INFORMATION_ACCOUNT = `${PANEL_INDIVIDUAL_BANKING_INFORMATION}/account`
const PANEL_INDIVIDUAL_BANKING_INFORMATION_COMMITMENTS = `${PANEL_INDIVIDUAL_BANKING_INFORMATION}/commitments`
const PANEL_INDIVIDUAL_BANKING_INFORMATION_TRANSACTION_HISTORY = `${PANEL_INDIVIDUAL_BANKING_INFORMATION}/transaction-history`
const PANEL_INDIVIDUAL_BANKING_INFORMATION_TRANSACTION_HISTORY_E_SERVICE = `${PANEL_INDIVIDUAL_BANKING_INFORMATION_TRANSACTION_HISTORY}-e-service`
const PANEL_INDIVIDUAL_BANKING_INFORMATION_TRANSACTION_HISTORY_E_SERVICE_DETAIL = (eServiceId: string) => `${PANEL_INDIVIDUAL_BANKING_INFORMATION_TRANSACTION_HISTORY_E_SERVICE}/${eServiceId}`
const PANEL_INDIVIDUAL_BANKING_INFORMATION_E_SERVICE_PORTAL = `${PANEL_INDIVIDUAL_BANKING_INFORMATION}/e-service-portal`
const PANEL_INDIVIDUAL_BANKING_INFORMATION_TRANSACTION_HISTORY_PERIOD_DETAIL = (periodId: string) => `${PANEL_INDIVIDUAL_BANKING_INFORMATION_TRANSACTION_HISTORY}/${periodId}`

const PANEL_JOINT_BANKING_INFORMATION = `${BANKING_INFO}/joint`
const PANEL_JOINT_BANKING_INFORMATION_ACCOUNT = `${PANEL_JOINT_BANKING_INFORMATION}/account`
const PANEL_JOINT_BANKING_INFORMATION_COMMITMENTS = `${PANEL_JOINT_BANKING_INFORMATION}/commitments`
const PANEL_JOINT_BANKING_INFORMATION_TRANSACTION_HISTORY = `${PANEL_JOINT_BANKING_INFORMATION}/transaction-history`
const PANEL_JOINT_BANKING_INFORMATION_TRANSACTION_HISTORY_E_SERVICE = `${PANEL_JOINT_BANKING_INFORMATION_TRANSACTION_HISTORY}-e-service`
const PANEL_JOINT_BANKING_INFORMATION_TRANSACTION_HISTORY_E_SERVICE_DETAIL = (eServiceId: string) => `${PANEL_JOINT_BANKING_INFORMATION_TRANSACTION_HISTORY_E_SERVICE}/${eServiceId}`
const PANEL_JOINT_BANKING_INFORMATION_E_SERVICE_PORTAL = `${PANEL_JOINT_BANKING_INFORMATION}/e-service-portal`
const PANEL_JOINT_BANKING_INFORMATION_TRANSACTION_HISTORY_PERIOD_DETAIL = (periodId: string) => `${PANEL_JOINT_BANKING_INFORMATION_TRANSACTION_HISTORY}/${periodId}`


const ROUTER_LINKS = {
  REMOTE: '/remote',

  SSO_LOGIN: '/auth/sso-login',

  HOME: '/',
  SEARCH: '/search',

  PANEL,

  PANEL_BASIC_INFORMATION: `${COMPREHENSIVE_INFO}/basic-information`,
  PANEL_INQUIRY_HISTORIES: `${COMPREHENSIVE_INFO}/inquiry-histories`,
  PANEL_ECONOMIC_INFORMATION: `${COMPREHENSIVE_INFO}/economic-information`,
  PANEL_LEGAL_REPRESENTATIVE_INFORMATION: `${COMPREHENSIVE_INFO}/legal-representative-information`,

  PANEL_INDIVIDUAL_BANKING_INFORMATION,
  PANEL_INDIVIDUAL_BANKING_INFORMATION_ACCOUNT,
  PANEL_INDIVIDUAL_BANKING_INFORMATION_ACCOUNT_DETAIL: (id: string | number) => `${PANEL_INDIVIDUAL_BANKING_INFORMATION_ACCOUNT}/${id}`,
  PANEL_INDIVIDUAL_BANKING_INFORMATION_COMMITMENTS,
  PANEL_INDIVIDUAL_BANKING_INFORMATION_COMMITMENTS_DETAIL: (id: string | number) => `${PANEL_INDIVIDUAL_BANKING_INFORMATION_COMMITMENTS}/${id}`,
  PANEL_INDIVIDUAL_BANKING_INFORMATION_E_SERVICE_PORTAL,
  PANEL_INDIVIDUAL_BANKING_INFORMATION_E_SERVICE_PORTAL_DETAIL: (id: string | number) => `${PANEL_INDIVIDUAL_BANKING_INFORMATION_E_SERVICE_PORTAL}/${id}`,
  PANEL_INDIVIDUAL_BANKING_INFORMATION_TRANSACTION_HISTORY,
  PANEL_INDIVIDUAL_BANKING_INFORMATION_TRANSACTION_HISTORY_PERIOD_DETAIL,
  PANEL_INDIVIDUAL_BANKING_INFORMATION_TRANSACTION_HISTORY_BRANCH_DETAIL: (periodId: string, branchId: string)=> `${PANEL_INDIVIDUAL_BANKING_INFORMATION_TRANSACTION_HISTORY_PERIOD_DETAIL(periodId)}/${branchId}`,
  PANEL_INDIVIDUAL_BANKING_INFORMATION_TRANSACTION_HISTORY_E_SERVICE,
  PANEL_INDIVIDUAL_BANKING_INFORMATION_TRANSACTION_HISTORY_E_SERVICE_DETAIL,
  PANEL_INDIVIDUAL_BANKING_INFORMATION_TRANSACTION_HISTORY_E_SERVICE_PERIOD_DETAIL: (eServiceId: string, periodId: string) => `${PANEL_INDIVIDUAL_BANKING_INFORMATION_TRANSACTION_HISTORY_E_SERVICE_DETAIL(eServiceId)}/${periodId}`,

  PANEL_JOINT_BANKING_INFORMATION,
  PANEL_JOINT_BANKING_INFORMATION_ACCOUNT,
  PANEL_JOINT_BANKING_INFORMATION_ACCOUNT_DETAIL: (id: string | number) => `${PANEL_JOINT_BANKING_INFORMATION_ACCOUNT}/${id}`,
  PANEL_JOINT_BANKING_INFORMATION_COMMITMENTS,
  PANEL_JOINT_BANKING_INFORMATION_COMMITMENTS_DETAIL: (id: string | number) => `${PANEL_JOINT_BANKING_INFORMATION_COMMITMENTS}/${id}`,
  PANEL_JOINT_BANKING_INFORMATION_E_SERVICE_PORTAL,
  PANEL_JOINT_BANKING_INFORMATION_E_SERVICE_PORTAL_DETAIL: (id: string | number) => `${PANEL_JOINT_BANKING_INFORMATION_E_SERVICE_PORTAL}/${id}`,
  PANEL_JOINT_BANKING_INFORMATION_TRANSACTION_HISTORY,
  PANEL_JOINT_BANKING_INFORMATION_TRANSACTION_HISTORY_PERIOD_DETAIL,
  PANEL_JOINT_BANKING_INFORMATION_TRANSACTION_HISTORY_BRANCH_DETAIL: (periodId: string, branchId: string)=> `${PANEL_JOINT_BANKING_INFORMATION_TRANSACTION_HISTORY_PERIOD_DETAIL(periodId)}/${branchId}`,
  PANEL_JOINT_BANKING_INFORMATION_TRANSACTION_HISTORY_E_SERVICE,
  PANEL_JOINT_BANKING_INFORMATION_TRANSACTION_HISTORY_E_SERVICE_DETAIL,
  PANEL_JOINT_BANKING_INFORMATION_TRANSACTION_HISTORY_E_SERVICE_PERIOD_DETAIL: (eServiceId: string, periodId: string) => `${PANEL_JOINT_BANKING_INFORMATION_TRANSACTION_HISTORY_E_SERVICE_DETAIL(eServiceId)}/${periodId}`,

  PANEL_BANKING_INFORMATION_FOR_ACCOUNTS_WITH_WITHDRAWAL_CONDITIONS: `${BANKING_INFO}/banking-information-for-accounts-with-withdrawal-conditions`,

  PANEL_CUSTOMER_RISK: `${COMPREHENSIVE_INFO}/customer-risk`,
  PANEL_SERVICE_HISTORY_RISK: `${COMPREHENSIVE_INFO}/service-history-risk`,
  PANEL_REGIONAL_RISK: `${COMPREHENSIVE_INFO}/reginal-risk`,
}

export default ROUTER_LINKS
