
const PANEL = '/panel'
const COMPREHENSIVE_INFO = `${PANEL}/comprehensive-info`
const PANEL_INDIVIDUAL_BANKING_INFORMATION = `${COMPREHENSIVE_INFO}/individual-banking-information`
const PANEL_INDIVIDUAL_BANKING_INFORMATION_ACCOUNT = `${PANEL_INDIVIDUAL_BANKING_INFORMATION}/account`
const PANEL_INDIVIDUAL_BANKING_INFORMATION_COMMITMENTS = `${PANEL_INDIVIDUAL_BANKING_INFORMATION}/commitments`

const PANEL_JOINT_BANKING_INFORMATION = `${COMPREHENSIVE_INFO}/joint-banking-information`
const PANEL_JOINT_BANKING_INFORMATION_ACCOUNT = `${PANEL_JOINT_BANKING_INFORMATION}/account`
const PANEL_JOINT_BANKING_INFORMATION_COMMITMENTS = `${PANEL_JOINT_BANKING_INFORMATION}/commitments`

const ROUTER_LINKS = {
  REMOTE: '/remote',

  SSO_LOGIN: '/auth/sso-login',

  HOME: '/',
  SEARCH: '/search',

  PANEL,

  PANEL_BASIC_INFORMATION: `${COMPREHENSIVE_INFO}/basic-information`,
  PANEL_INQUIRY_HISTORIES: `${COMPREHENSIVE_INFO}/inquiry-histories`,
  PANEL_ECONOMIC_INFORMATION: `${COMPREHENSIVE_INFO}/economic-information`,
  PANEL_LEGAL_REPRESENTATIVE_INFORMATION: `${COMPREHENSIVE_INFO}/legal-representative-information`,

  PANEL_INDIVIDUAL_BANKING_INFORMATION,
  PANEL_INDIVIDUAL_BANKING_INFORMATION_ACCOUNT,
  PANEL_INDIVIDUAL_BANKING_INFORMATION_ACCOUNT_DETAIL: (id: string | number) => `${PANEL_INDIVIDUAL_BANKING_INFORMATION_ACCOUNT}/${id}`,
  PANEL_INDIVIDUAL_BANKING_INFORMATION_COMMITMENTS,
  PANEL_INDIVIDUAL_BANKING_INFORMATION_COMMITMENTS_DETAIL: (id: string | number) => `${PANEL_INDIVIDUAL_BANKING_INFORMATION_COMMITMENTS}/${id}`,

  PANEL_JOINT_BANKING_INFORMATION,
  PANEL_JOINT_BANKING_INFORMATION_ACCOUNT,
  PANEL_JOINT_BANKING_INFORMATION_ACCOUNT_DETAIL: (id: string | number) => `${PANEL_JOINT_BANKING_INFORMATION_ACCOUNT}/${id}`,
  PANEL_JOINT_BANKING_INFORMATION_COMMITMENTS,
  PANEL_JOINT_BANKING_INFORMATION_COMMITMENTS_DETAIL: (id: string | number) => `${PANEL_JOINT_BANKING_INFORMATION_COMMITMENTS}/${id}`,

  PANEL_BANKING_INFORMATION_FOR_ACCOUNTS_WITH_WITHDRAWAL_CONDITIONS: `${COMPREHENSIVE_INFO}/banking-information-for-accounts-with-withdrawal-conditions`,
  PANEL_CUSTOMER_RISK: `${COMPREHENSIVE_INFO}/customer-risk`,
  PANEL_SERVICE_HISTORY_RISK: `${COMPREHENSIVE_INFO}/service-history-risk`,
  PANEL_REGIONAL_RISK: `${COMPREHENSIVE_INFO}/reginal-risk`,

  PANEL_: `${COMPREHENSIVE_INFO}/reginal-risk`,
}

export default ROUTER_LINKS