import type {TableColumnType} from "../../../../../../components/others/Table/TableExports.ts";

export const PANEL_TRANSACTION_HISTORY_BY_BRANCH_DETAIL_TABLE_COLUMNS_KEYS = {
  ACCOUNT_NUMBER: 'accountNumber',
  OPERATION_TYPE: 'operationType',
  CREDITOR_AMOUNT: 'creditorAmount',
  DEBTOR_AMOUNT: 'debtorAmount',
  BALANCE: 'balance',
  PERSONNEL_CODE: 'personnelCode',
  FIRST_NAME: 'firstName',
  LAST_NAME: 'lastName',
} as const;

export const PANEL_TRANSACTION_HISTORY_BY_BRANCH_DETAIL_TABLE_COLUMNS: TableColumnType[] = [
  {
    label: 'شماره حساب',
    accessor: PANEL_TRANSACTION_HISTORY_BY_BRANCH_DETAIL_TABLE_COLUMNS_KEYS.ACCOUNT_NUMBER,
  },
  {
    label: 'نوع عملیات',
    accessor: PANEL_TRANSACTION_HISTORY_BY_BRANCH_DETAIL_TABLE_COLUMNS_KEYS.OPERATION_TYPE,
  },
  {
    label: 'بستانکار',
    accessor: PANEL_TRANSACTION_HISTORY_BY_BRANCH_DETAIL_TABLE_COLUMNS_KEYS.CREDITOR_AMOUNT,
  },
  {
    label: 'بدهکار',
    accessor: PANEL_TRANSACTION_HISTORY_BY_BRANCH_DETAIL_TABLE_COLUMNS_KEYS.DEBTOR_AMOUNT,
  },
  {
    label: 'بستانکار - بدهکار',
    accessor: PANEL_TRANSACTION_HISTORY_BY_BRANCH_DETAIL_TABLE_COLUMNS_KEYS.BALANCE,
  },
  {
    label: 'کد پرسنلی',
    accessor: PANEL_TRANSACTION_HISTORY_BY_BRANCH_DETAIL_TABLE_COLUMNS_KEYS.PERSONNEL_CODE,
  },
  {
    label: 'نام',
    accessor: PANEL_TRANSACTION_HISTORY_BY_BRANCH_DETAIL_TABLE_COLUMNS_KEYS.FIRST_NAME,
  },
  {
    label: 'نام خانوادگی',
    accessor: PANEL_TRANSACTION_HISTORY_BY_BRANCH_DETAIL_TABLE_COLUMNS_KEYS.LAST_NAME,
  },
];

export const PANEL_TRANSACTION_HISTORY_BY_BRANCH_DETAIL_TABLE_FAKE_DATA = [
  {
    id: 1,
    [PANEL_TRANSACTION_HISTORY_BY_BRANCH_DETAIL_TABLE_COLUMNS_KEYS.ACCOUNT_NUMBER]: '123456789012',
    [PANEL_TRANSACTION_HISTORY_BY_BRANCH_DETAIL_TABLE_COLUMNS_KEYS.OPERATION_TYPE]: 'واریز',
    [PANEL_TRANSACTION_HISTORY_BY_BRANCH_DETAIL_TABLE_COLUMNS_KEYS.CREDITOR_AMOUNT]: '850,000,000',
    [PANEL_TRANSACTION_HISTORY_BY_BRANCH_DETAIL_TABLE_COLUMNS_KEYS.DEBTOR_AMOUNT]: '120,000,000',
    [PANEL_TRANSACTION_HISTORY_BY_BRANCH_DETAIL_TABLE_COLUMNS_KEYS.BALANCE]: '730,000,000',
    [PANEL_TRANSACTION_HISTORY_BY_BRANCH_DETAIL_TABLE_COLUMNS_KEYS.PERSONNEL_CODE]: '100245',
    [PANEL_TRANSACTION_HISTORY_BY_BRANCH_DETAIL_TABLE_COLUMNS_KEYS.FIRST_NAME]: 'علی',
    [PANEL_TRANSACTION_HISTORY_BY_BRANCH_DETAIL_TABLE_COLUMNS_KEYS.LAST_NAME]: 'محمدی',
  },
  {
    id: 2,
    [PANEL_TRANSACTION_HISTORY_BY_BRANCH_DETAIL_TABLE_COLUMNS_KEYS.ACCOUNT_NUMBER]: '987654321098',
    [PANEL_TRANSACTION_HISTORY_BY_BRANCH_DETAIL_TABLE_COLUMNS_KEYS.OPERATION_TYPE]: 'برداشت',
    [PANEL_TRANSACTION_HISTORY_BY_BRANCH_DETAIL_TABLE_COLUMNS_KEYS.CREDITOR_AMOUNT]: '300,000,000',
    [PANEL_TRANSACTION_HISTORY_BY_BRANCH_DETAIL_TABLE_COLUMNS_KEYS.DEBTOR_AMOUNT]: '450,000,000',
    [PANEL_TRANSACTION_HISTORY_BY_BRANCH_DETAIL_TABLE_COLUMNS_KEYS.BALANCE]: '-150,000,000',
    [PANEL_TRANSACTION_HISTORY_BY_BRANCH_DETAIL_TABLE_COLUMNS_KEYS.PERSONNEL_CODE]: '100378',
    [PANEL_TRANSACTION_HISTORY_BY_BRANCH_DETAIL_TABLE_COLUMNS_KEYS.FIRST_NAME]: 'مریم',
    [PANEL_TRANSACTION_HISTORY_BY_BRANCH_DETAIL_TABLE_COLUMNS_KEYS.LAST_NAME]: 'احمدی',
  },
];
