import type {TableColumnType} from "../../../../../../../components/others/Table/TableExports.ts";

export const INDIVIDUAL_ACCOUNT_BLOCK_HISTORY_TABLE_COLUMNS_KEYS = {
  BLOCK_AMOUNT: 'blockAmount',
  BLOCK_APPLY_DATE: 'blockApplyDate',
  BLOCK_REMOVE_DATE: 'blockRemoveDate',
  REASON_CODE: 'reasonCode',
  BLOCK_REASON_DESCRIPTION: 'blockReasonDescription',
} as const;

export const INDIVIDUAL_ACCOUNT_BLOCK_HISTORY_TABLE_COLUMNS: TableColumnType[] = [
  {
    label: 'مبلغ مسدودی',
    accessor: INDIVIDUAL_ACCOUNT_BLOCK_HISTORY_TABLE_COLUMNS_KEYS.BLOCK_AMOUNT,
  },
  {
    label: 'تاریخ اعمال مسدودی',
    accessor: INDIVIDUAL_ACCOUNT_BLOCK_HISTORY_TABLE_COLUMNS_KEYS.BLOCK_APPLY_DATE,
  },
  {
    label: 'تاریخ رفع مسدودی',
    accessor: INDIVIDUAL_ACCOUNT_BLOCK_HISTORY_TABLE_COLUMNS_KEYS.BLOCK_REMOVE_DATE,
  },
  {
    label: 'کد علت',
    accessor: INDIVIDUAL_ACCOUNT_BLOCK_HISTORY_TABLE_COLUMNS_KEYS.REASON_CODE,
  },
  {
    label: 'شرح علت مسدودی',
    accessor: INDIVIDUAL_ACCOUNT_BLOCK_HISTORY_TABLE_COLUMNS_KEYS.BLOCK_REASON_DESCRIPTION,
  },
];

export const INDIVIDUAL_ACCOUNT_BLOCK_HISTORY_TABLE_FAKE_DATA = [
  {
    id: 1,
    [INDIVIDUAL_ACCOUNT_BLOCK_HISTORY_TABLE_COLUMNS_KEYS.BLOCK_AMOUNT]: '150,000,000 ریال',
    [INDIVIDUAL_ACCOUNT_BLOCK_HISTORY_TABLE_COLUMNS_KEYS.BLOCK_APPLY_DATE]: '1403/01/05',
    [INDIVIDUAL_ACCOUNT_BLOCK_HISTORY_TABLE_COLUMNS_KEYS.BLOCK_REMOVE_DATE]: '1403/01/25',
    [INDIVIDUAL_ACCOUNT_BLOCK_HISTORY_TABLE_COLUMNS_KEYS.REASON_CODE]: '401',
    [INDIVIDUAL_ACCOUNT_BLOCK_HISTORY_TABLE_COLUMNS_KEYS.BLOCK_REASON_DESCRIPTION]: 'دستور قضایی',
  },
  {
    id: 2,
    [INDIVIDUAL_ACCOUNT_BLOCK_HISTORY_TABLE_COLUMNS_KEYS.BLOCK_AMOUNT]: '80,000,000 ریال',
    [INDIVIDUAL_ACCOUNT_BLOCK_HISTORY_TABLE_COLUMNS_KEYS.BLOCK_APPLY_DATE]: '1402/12/10',
    [INDIVIDUAL_ACCOUNT_BLOCK_HISTORY_TABLE_COLUMNS_KEYS.BLOCK_REMOVE_DATE]: '-',
    [INDIVIDUAL_ACCOUNT_BLOCK_HISTORY_TABLE_COLUMNS_KEYS.REASON_CODE]: '215',
    [INDIVIDUAL_ACCOUNT_BLOCK_HISTORY_TABLE_COLUMNS_KEYS.BLOCK_REASON_DESCRIPTION]: 'بدهی معوق',
  },
  {
    id: 3,
    [INDIVIDUAL_ACCOUNT_BLOCK_HISTORY_TABLE_COLUMNS_KEYS.BLOCK_AMOUNT]: '300,000,000 ریال',
    [INDIVIDUAL_ACCOUNT_BLOCK_HISTORY_TABLE_COLUMNS_KEYS.BLOCK_APPLY_DATE]: '1403/02/14',
    [INDIVIDUAL_ACCOUNT_BLOCK_HISTORY_TABLE_COLUMNS_KEYS.BLOCK_REMOVE_DATE]: '1403/03/01',
    [INDIVIDUAL_ACCOUNT_BLOCK_HISTORY_TABLE_COLUMNS_KEYS.REASON_CODE]: '330',
    [INDIVIDUAL_ACCOUNT_BLOCK_HISTORY_TABLE_COLUMNS_KEYS.BLOCK_REASON_DESCRIPTION]: 'درخواست مشتری',
  },
];
