import type {TableColumnType} from "../../../../../../components/others/Table/TableExports.ts";
import ACTIONS_COLUMN from "../../../../../../components/others/Table/constances/actions/actionsColumn.ts";
import getLast13Months from "../../../../../../utils/dateAndTIme/momentJalaliDateTime/getLast13Months.ts";

export const PANEL_INDIVIDUAL_TRANSACTION_HISTORY_ONSITE_MAX_COUNT_TABLE_COLUMNS_KEYS = {
  MONTH: 'month',
  VISIT_COUNT: 'visitCount',
  TOTAL_CREDITOR: 'totalCreditor',
  TOTAL_DEBTOR: 'totalDebtor',
  BALANCE: 'balance',
  FROM_DATE: 'fromDate',
  TO_DATE: 'toDate',
} as const;

export const PANEL_INDIVIDUAL_TRANSACTION_HISTORY_ONSITE_MAX_COUNT_TABLE_COLUMNS: TableColumnType[] = [
  {
    label: 'ماه',
    accessor: PANEL_INDIVIDUAL_TRANSACTION_HISTORY_ONSITE_MAX_COUNT_TABLE_COLUMNS_KEYS.MONTH,
  },
  {
    label: 'از تاریخ',
    accessor: PANEL_INDIVIDUAL_TRANSACTION_HISTORY_ONSITE_MAX_COUNT_TABLE_COLUMNS_KEYS.FROM_DATE,
  },
  {
    label: 'تا تاریخ',
    accessor: PANEL_INDIVIDUAL_TRANSACTION_HISTORY_ONSITE_MAX_COUNT_TABLE_COLUMNS_KEYS.TO_DATE,
  },
  {
    label: 'تعداد مراجعه',
    accessor: PANEL_INDIVIDUAL_TRANSACTION_HISTORY_ONSITE_MAX_COUNT_TABLE_COLUMNS_KEYS.VISIT_COUNT,
  },
  {
    label: 'مجموع بستانکار',
    accessor: PANEL_INDIVIDUAL_TRANSACTION_HISTORY_ONSITE_MAX_COUNT_TABLE_COLUMNS_KEYS.TOTAL_CREDITOR,
  },
  {
    label: 'مجموع بدهکار',
    accessor: PANEL_INDIVIDUAL_TRANSACTION_HISTORY_ONSITE_MAX_COUNT_TABLE_COLUMNS_KEYS.TOTAL_DEBTOR,
  },
  {
    label: 'مجموع بستانکار - مجموع بدهکار',
    accessor: PANEL_INDIVIDUAL_TRANSACTION_HISTORY_ONSITE_MAX_COUNT_TABLE_COLUMNS_KEYS.BALANCE,
  },
  ACTIONS_COLUMN
];

export const PANEL_INDIVIDUAL_TRANSACTION_HISTORY_ONSITE_MAX_COUNT_TABLE_FAKE_DATA = getLast13Months().map((item, index) => ({
  id: index + 1,
  [PANEL_INDIVIDUAL_TRANSACTION_HISTORY_ONSITE_MAX_COUNT_TABLE_COLUMNS_KEYS.MONTH]: item.monthName,
  [PANEL_INDIVIDUAL_TRANSACTION_HISTORY_ONSITE_MAX_COUNT_TABLE_COLUMNS_KEYS.FROM_DATE]: item.fromDate,
  [PANEL_INDIVIDUAL_TRANSACTION_HISTORY_ONSITE_MAX_COUNT_TABLE_COLUMNS_KEYS.TO_DATE]: item.toDate,
  [PANEL_INDIVIDUAL_TRANSACTION_HISTORY_ONSITE_MAX_COUNT_TABLE_COLUMNS_KEYS.VISIT_COUNT]: 12,
  [PANEL_INDIVIDUAL_TRANSACTION_HISTORY_ONSITE_MAX_COUNT_TABLE_COLUMNS_KEYS.TOTAL_CREDITOR]: '850,000,000',
  [PANEL_INDIVIDUAL_TRANSACTION_HISTORY_ONSITE_MAX_COUNT_TABLE_COLUMNS_KEYS.TOTAL_DEBTOR]: '420,000,000',
  [PANEL_INDIVIDUAL_TRANSACTION_HISTORY_ONSITE_MAX_COUNT_TABLE_COLUMNS_KEYS.BALANCE]: '430,000,000',
}))
