import type {TableColumnType} from "../../../../../components/others/Table/TableExports.ts";
import Tag from "../../../../../components/others/Tag/Tag.tsx";
import {
  PANEL_INDIVIDUAL_CARD_INFO_TABLE_COLUMNS,
  PANEL_INDIVIDUAL_CARD_INFO_TABLE_COLUMNS_KEYS
} from "../../individual/card/index.constances.tsx";


export const PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS = {
  SHARED_CUSTOMER_NUMBER: 'sharedCustomerNumber',
  ...PANEL_INDIVIDUAL_CARD_INFO_TABLE_COLUMNS_KEYS,
} as const;

export const PANEL_JOINT_CARD_INFO_TABLE_COLUMNS: TableColumnType[] = [
  {
    label: 'شماره مشتری مشترک',
    accessor: PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS.SHARED_CUSTOMER_NUMBER,
  },
  ...PANEL_INDIVIDUAL_CARD_INFO_TABLE_COLUMNS,
];

export const PANEL_JOINT_CARD_INFO_TABLE_FAKE_DATA = [
  {
    id: 1,
    [PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS.SHARED_CUSTOMER_NUMBER]: '0103456789001',
    [PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS.CARD_NUMBER]: '6037991234567890',
    [PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS.CARD_ACCOUNT_NUMBER]: '0103456789001',
    [PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS.CARD_STATUS]: (
      <Tag text='فعال' color='green' variant='fade'/>
    ),
    [PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS.CARD_TYPE]: 'دبیت',
    [PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS.ISSUE_DATE]: '1402/06/01',
    [PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS.EXPIRY_DATE]: '1406/06/01',
    [PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS.ISSUE_BRANCH_CODE]: '1021',
    [PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS.ISSUE_BRANCH_NAME]: 'شعبه ولیعصر',
    [PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS.ISSUE_REGION_CODE]: '10',
    [PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS.ISSUE_REGION_NAME]: 'منطقه مرکزی',
    [PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS.ISSUER_PERSONNEL_CODE]: '45872',
    [PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS.ISSUER_NAME]: 'علی محمدی',
  },
  {
    id: 2,
    [PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS.SHARED_CUSTOMER_NUMBER]: '0103456789001',
    [PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS.CARD_NUMBER]: '5892109876543210',
    [PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS.CARD_ACCOUNT_NUMBER]: '0109876543210',
    [PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS.CARD_STATUS]: (
      <Tag text='مسدود' color='red' variant='fade'/>
    ),
    [PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS.CARD_TYPE]: 'دبیت',
    [PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS.ISSUE_DATE]: '1401/12/15',
    [PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS.EXPIRY_DATE]: '1405/12/15',
    [PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS.ISSUE_BRANCH_CODE]: '2045',
    [PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS.ISSUE_BRANCH_NAME]: 'شعبه انقلاب',
    [PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS.ISSUE_REGION_CODE]: '20',
    [PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS.ISSUE_REGION_NAME]: 'منطقه غرب',
    [PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS.ISSUER_PERSONNEL_CODE]: '56321',
    [PANEL_JOINT_CARD_INFO_TABLE_COLUMNS_KEYS.ISSUER_NAME]: 'مریم رضایی',
  },
];
