import type { TableColumnType } from "../../../../components/others/Table/TableExports.ts";

export const PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS = {
  INCOME_SOURCE_TITLE: 'incomeSourceTitle',
  ANNUAL_INCOME_MAX: 'annualIncomeMax',
  TRANSACTION_ORIGIN_DEST: 'transactionOriginDest',
  ANNOUNCEMENT_DATE: 'announcementDate',
  FROM_DATE: 'fromDate',
  TO_DATE: 'toDate',
  REGISTRATION_DATE: 'registrationDate',
} as const;

export const PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS: TableColumnType[] = [
  {
    label: 'عنوان منبع درآمد',
    accessor:
    PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.INCOME_SOURCE_TITLE,
  },
  {
    label: 'حداکثر مبلغ درآمد سالیانه',
    accessor:
    PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.ANNUAL_INCOME_MAX,
  },
  {
    label: 'انواع مبدا و مقصد مورد انتظار تراکنش',
    accessor:
    PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.TRANSACTION_ORIGIN_DEST,
  },
  {
    label: 'تاریخ اعلام',
    accessor:
    PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.ANNOUNCEMENT_DATE,
  },
  {
    label: 'از تاریخ',
    accessor:
    PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.FROM_DATE,
  },
  {
    label: 'تا تاریخ',
    accessor:
    PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.TO_DATE,
  },
  {
    label: 'تاریخ ثبت',
    accessor:
    PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.REGISTRATION_DATE,
  },
];

export const PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_FAKE_DATA = [
  {
    id: 1,
    [PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.INCOME_SOURCE_TITLE]:
      'سرمایه‌گذاری در بورس',
    [PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.ANNUAL_INCOME_MAX]:
      '800000',
    [PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.TRANSACTION_ORIGIN_DEST]:
      'BrokerAccount; BankAccount',
    [PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.ANNOUNCEMENT_DATE]:
      '2026-02-10',
    [PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.FROM_DATE]:
      '2026-01-01',
    [PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.TO_DATE]:
      '2026-12-31',
    [PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.REGISTRATION_DATE]:
      '2026-02-15',
  },
  {
    id: 2,
    [PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.INCOME_SOURCE_TITLE]:
      'فروش آنلاین محصولات',
    [PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.ANNUAL_INCOME_MAX]:
      '1200000',
    [PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.TRANSACTION_ORIGIN_DEST]:
      'OnlineGateway; PersonalAccount',
    [PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.ANNOUNCEMENT_DATE]:
      '2026-03-05',
    [PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.FROM_DATE]:
      '2026-02-01',
    [PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.TO_DATE]:
      '2026-11-30',
    [PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.REGISTRATION_DATE]:
      '2026-03-06',
  },
  {
    id: 3,
    [PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.INCOME_SOURCE_TITLE]:
      'اجاره ملک',
    [PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.ANNUAL_INCOME_MAX]:
      '1500000',
    [PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.TRANSACTION_ORIGIN_DEST]:
      'Tenant; BankAccount',
    [PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.ANNOUNCEMENT_DATE]:
      '2026-01-20',
    [PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.FROM_DATE]:
      '2026-01-01',
    [PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.TO_DATE]:
      '2026-12-31',
    [PANEL_ECONOMIC_SECONDARY_SOURCE_OF_INCOME_INFORMATION_TABLE_COLUMNS_KEYS.REGISTRATION_DATE]:
      '2026-01-22',
  },
];
