import type {TableColumnType} from "../../../../../../../components/others/Table/TableExports.ts";

export const INDIVIDUAL_ACCOUNT_TRANSACTION_INFO_TABLE_COLUMNS_KEYS = {
  TRANSACTION_PERIOD: 'transactionPeriod',
  TOTAL_CREDIT: 'totalCredit',
  TOTAL_DEBIT: 'totalDebit',
  BALANCE_DIFFERENCE: 'balanceDifference',
  FROM_DATE: 'fromDate',
  TO_DATE: 'toDate',
} as const;

export const INDIVIDUAL_ACCOUNT_TRANSACTION_INFO_TABLE_COLUMNS: TableColumnType[] = [
  {
    label: 'بازه زمانی گردش حساب',
    accessor: INDIVIDUAL_ACCOUNT_TRANSACTION_INFO_TABLE_COLUMNS_KEYS.TRANSACTION_PERIOD,
  },
  {
    label: 'مجموع بستانکار',
    accessor: INDIVIDUAL_ACCOUNT_TRANSACTION_INFO_TABLE_COLUMNS_KEYS.TOTAL_CREDIT,
  },
  {
    label: 'مجموع بدهکار',
    accessor: INDIVIDUAL_ACCOUNT_TRANSACTION_INFO_TABLE_COLUMNS_KEYS.TOTAL_DEBIT,
  },
  {
    label: 'مجموع بستانکار - مجموع بدهکار',
    accessor: INDIVIDUAL_ACCOUNT_TRANSACTION_INFO_TABLE_COLUMNS_KEYS.BALANCE_DIFFERENCE,
  },
  {
    label: 'از تاریخ',
    accessor: INDIVIDUAL_ACCOUNT_TRANSACTION_INFO_TABLE_COLUMNS_KEYS.FROM_DATE,
  },
  {
    label: 'تا تاریخ',
    accessor: INDIVIDUAL_ACCOUNT_TRANSACTION_INFO_TABLE_COLUMNS_KEYS.TO_DATE,
  },
];

export const INDIVIDUAL_ACCOUNT_TRANSACTION_INFO_TABLE_FAKE_DATA = [
  {
    id: 1,
    [INDIVIDUAL_ACCOUNT_TRANSACTION_INFO_TABLE_COLUMNS_KEYS.TRANSACTION_PERIOD]: 'ماهانه',
    [INDIVIDUAL_ACCOUNT_TRANSACTION_INFO_TABLE_COLUMNS_KEYS.TOTAL_CREDIT]: '850,000,000 ریال',
    [INDIVIDUAL_ACCOUNT_TRANSACTION_INFO_TABLE_COLUMNS_KEYS.TOTAL_DEBIT]: '620,000,000 ریال',
    [INDIVIDUAL_ACCOUNT_TRANSACTION_INFO_TABLE_COLUMNS_KEYS.BALANCE_DIFFERENCE]: '230,000,000 ریال',
    [INDIVIDUAL_ACCOUNT_TRANSACTION_INFO_TABLE_COLUMNS_KEYS.FROM_DATE]: '1403/01/01',
    [INDIVIDUAL_ACCOUNT_TRANSACTION_INFO_TABLE_COLUMNS_KEYS.TO_DATE]: '1403/01/31',
  },
  {
    id: 2,
    [INDIVIDUAL_ACCOUNT_TRANSACTION_INFO_TABLE_COLUMNS_KEYS.TRANSACTION_PERIOD]: 'سه ماهه',
    [INDIVIDUAL_ACCOUNT_TRANSACTION_INFO_TABLE_COLUMNS_KEYS.TOTAL_CREDIT]: '2,450,000,000 ریال',
    [INDIVIDUAL_ACCOUNT_TRANSACTION_INFO_TABLE_COLUMNS_KEYS.TOTAL_DEBIT]: '2,100,000,000 ریال',
    [INDIVIDUAL_ACCOUNT_TRANSACTION_INFO_TABLE_COLUMNS_KEYS.BALANCE_DIFFERENCE]: '350,000,000 ریال',
    [INDIVIDUAL_ACCOUNT_TRANSACTION_INFO_TABLE_COLUMNS_KEYS.FROM_DATE]: '1402/10/01',
    [INDIVIDUAL_ACCOUNT_TRANSACTION_INFO_TABLE_COLUMNS_KEYS.TO_DATE]: '1402/12/29',
  },
  {
    id: 3,
    [INDIVIDUAL_ACCOUNT_TRANSACTION_INFO_TABLE_COLUMNS_KEYS.TRANSACTION_PERIOD]: 'سالانه',
    [INDIVIDUAL_ACCOUNT_TRANSACTION_INFO_TABLE_COLUMNS_KEYS.TOTAL_CREDIT]: '9,800,000,000 ریال',
    [INDIVIDUAL_ACCOUNT_TRANSACTION_INFO_TABLE_COLUMNS_KEYS.TOTAL_DEBIT]: '8,950,000,000 ریال',
    [INDIVIDUAL_ACCOUNT_TRANSACTION_INFO_TABLE_COLUMNS_KEYS.BALANCE_DIFFERENCE]: '850,000,000 ریال',
    [INDIVIDUAL_ACCOUNT_TRANSACTION_INFO_TABLE_COLUMNS_KEYS.FROM_DATE]: '1402/01/01',
    [INDIVIDUAL_ACCOUNT_TRANSACTION_INFO_TABLE_COLUMNS_KEYS.TO_DATE]: '1402/12/29',
  },
];
