import type {TableColumnType} from "../../../../../components/others/Table/TableExports.ts";
import TABLE_RENDER_TYPES from "../../../../../components/others/Table/constances/renderTypes.ts";
import Tag from "../../../../../components/others/Tag/Tag.tsx";
import ACTIONS_COLUMN from "../../../../../components/others/Table/constances/actionsColumn.ts";


export const PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS = {
  ACCOUNT_NUMBER: 'accountNumber',
  ACCOUNT_STATUS: 'accountStatus',
  ACCOUNT_SUB_TYPE: 'accountSubType',
  SAYYAH_ID: 'sayyahId',
  OPEN_DATE: 'openDate',
  OPEN_PURPOSE: 'openPurpose',
  BUSINESS_TYPE: 'businessType',
  OPEN_BRANCH_CODE: 'openBranchCode',
  OPEN_BRANCH_NAME: 'openBranchName',
  OPEN_REGION_CODE: 'openRegionCode',
  OPEN_REGION_NAME: 'openRegionName',
  OPENER_PERSONNEL_CODE: 'openerPersonnelCode',
  OPENER_NAME: 'openerName',
} as const;

export const PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS: TableColumnType[] = [
  {
    label: 'شماره حساب',
    accessor: PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.ACCOUNT_NUMBER,
  },
  {
    label: 'وضعیت حساب',
    accessor: PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.ACCOUNT_STATUS,
  },
  {
    label: 'زیر نوع حساب',
    accessor: PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.ACCOUNT_SUB_TYPE,
  },
  {
    label: 'شناسه سیاح',
    accessor: PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.SAYYAH_ID,
  },
  {
    label: 'تاریخ افتتاح',
    accessor: PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.OPEN_DATE,
  },
  {
    label: 'هدف افتتاح',
    accessor: PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.OPEN_PURPOSE,
  },
  {
    label: 'تجاری/غیرتجاری',
    accessor: PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.BUSINESS_TYPE,
  },
  {
    label: 'کد شعبه افتتاح',
    accessor: PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.OPEN_BRANCH_CODE,
  },
  {
    label: 'نام شعبه',
    accessor: PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.OPEN_BRANCH_NAME,
  },
  {
    label: 'کد منطقه افتتاح',
    accessor: PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.OPEN_REGION_CODE,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
  {
    label: 'نام منطقه',
    accessor: PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.OPEN_REGION_NAME,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
  {
    label: 'کدپرسنلی افتتاح کننده',
    accessor: PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.OPENER_PERSONNEL_CODE,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
  {
    label: 'نام و نام خانوادگی افتتاح کننده',
    accessor: PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.OPENER_NAME,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN
  },
  ACTIONS_COLUMN
];

export const PANEL_INDIVIDUAL_BANK_INFO_TABLE_FAKE_DATA = [
  {
    id: 1,
    [PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.ACCOUNT_NUMBER]: '0103456789001',
    [PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.ACCOUNT_STATUS]: <Tag text='فعال' color='green' variant='fade'/>,
    [PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.ACCOUNT_SUB_TYPE]: 'جاری',
    [PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.SAYYAH_ID]: 'SY123456789',
    [PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.OPEN_DATE]: '1402/05/12',
    [PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.OPEN_PURPOSE]: 'پس‌انداز',
    [PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.BUSINESS_TYPE]: 'غیرتجاری',
    [PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.OPEN_BRANCH_CODE]: '1021',
    [PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.OPEN_BRANCH_NAME]: 'شعبه ولیعصر',
    [PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.OPEN_REGION_CODE]: '10',
    [PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.OPEN_REGION_NAME]: 'منطقه مرکزی',
    [PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.OPENER_PERSONNEL_CODE]: '45872',
    [PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.OPENER_NAME]: 'علی محمدی',
  },
  {
    id: 2,
    [PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.ACCOUNT_NUMBER]: '0109876543210',
    [PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.ACCOUNT_STATUS]: <Tag text='غیرفعال' color='red' variant='fade'/>,
    [PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.ACCOUNT_SUB_TYPE]: 'پس‌انداز',
    [PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.SAYYAH_ID]: 'SY987654321',
    [PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.OPEN_DATE]: '1401/11/03',
    [PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.OPEN_PURPOSE]: 'حقوق و دستمزد',
    [PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.BUSINESS_TYPE]: 'غیرتجاری',
    [PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.OPEN_BRANCH_CODE]: '2045',
    [PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.OPEN_BRANCH_NAME]: 'شعبه انقلاب',
    [PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.OPEN_REGION_CODE]: '20',
    [PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.OPEN_REGION_NAME]: 'منطقه غرب',
    [PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.OPENER_PERSONNEL_CODE]: '56321',
    [PANEL_INDIVIDUAL_BANK_INFO_TABLE_COLUMNS_KEYS.OPENER_NAME]: 'مریم رضایی',
  },
];