import type {TableColumnType} from "../../../../../components/others/Table/TableExports.ts";
import Tag from "../../../../../components/others/Tag/Tag.tsx";
import {
  PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS,
  PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS
} from "../../individual/commitments/index.constances.tsx";


export const PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS = {
  SHARED_CUSTOMER_NUMBER: 'sharedCustomerNumber',
  ...PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS,
} as const;

export const PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS: TableColumnType[] = [
  {
    label: 'شماره مشتری مشترک',
    accessor: PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.SHARED_CUSTOMER_NUMBER,
  },
  ...PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS,
];

export const PANEL_JOINT_COMMITMENTS_TABLE_FAKE_DATA = [
  {
    id: 1,
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.SHARED_CUSTOMER_NUMBER]: '0103456789001',
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.INDIRECT_COMMITMENT]: 'بله',
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.COMMITMENT_NUMBER]: 'COM-1403001',
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.PRINCIPAL_AMOUNT]: '3,000,000,000 ریال',
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.TOTAL_AMOUNT]: '3,450,000,000 ریال',
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.INTEREST_RATE]: '15%',
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.COMMITMENT_TYPE]: 'ضمانت نامه',
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.STATUS]: (
      <Tag text='فعال' color='green' variant='fade'/>
    ),
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.CENTRAL_BANK_CONTRACT_NUMBER]: 'CB-987654',
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.ALLOCATION_DATE]: '1402/04/20',
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.END_DATE]: '1404/04/20',
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.BRANCH_CODE]: '1102',
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.BRANCH_NAME]: 'شعبه ونک',
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.REGION_NAME]: 'منطقه شمال',
  },
  {
    id: 2,
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.SHARED_CUSTOMER_NUMBER]: '0103456789001',
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.INDIRECT_COMMITMENT]: 'خیر',
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.COMMITMENT_NUMBER]: 'COM-1403002',
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.PRINCIPAL_AMOUNT]: '1,200,000,000 ریال',
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.TOTAL_AMOUNT]: '1,350,000,000 ریال',
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.INTEREST_RATE]: '12%',
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.COMMITMENT_TYPE]: 'اعتبار اسنادی',
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.STATUS]: (
      <Tag text='پایان یافته' color='blue' variant='fade'/>
    ),
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.CENTRAL_BANK_CONTRACT_NUMBER]: 'CB-123456',
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.ALLOCATION_DATE]: '1400/09/10',
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.END_DATE]: '1403/09/10',
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.BRANCH_CODE]: '2045',
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.BRANCH_NAME]: 'شعبه انقلاب',
    [PANEL_JOINT_COMMITMENTS_TABLE_COLUMNS_KEYS.REGION_NAME]: 'منطقه غرب',
  },
];
