import type {TableColumnType} from "../../../../../components/others/Table/TableExports.ts";
import TABLE_RENDER_TYPES from "../../../../../components/others/Table/constances/renderTypes.ts";
import Tag from "../../../../../components/others/Tag/Tag.tsx";
import ACTIONS_COLUMN from "../../../../../components/others/Table/constances/actionsColumn.ts";

export const PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS = {
  INDIRECT_COMMITMENT: 'indirectCommitment',
  COMMITMENT_NUMBER: 'commitmentNumber',
  PRINCIPAL_AMOUNT: 'principalAmount',
  TOTAL_AMOUNT: 'totalAmount',
  INTEREST_RATE: 'interestRate',
  COMMITMENT_TYPE: 'commitmentType',
  STATUS: 'status',
  CENTRAL_BANK_CONTRACT_NUMBER: 'centralBankContractNumber',
  ALLOCATION_DATE: 'allocationDate',
  END_DATE: 'endDate',
  BRANCH_CODE: 'branchCode',
  BRANCH_NAME: 'branchName',
  REGION_NAME: 'regionName',
} as const;

export const PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS: TableColumnType[] = [
  {
    label: 'تعهدات غیرمستقیم',
    accessor: PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.INDIRECT_COMMITMENT,
  },
  {
    label: 'شماره تعهدات',
    accessor: PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.COMMITMENT_NUMBER,
  },
  {
    label: 'مبلغ اصل تعهدات',
    accessor: PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.PRINCIPAL_AMOUNT,
  },
  {
    label: 'مبلغ کل تعهدات',
    accessor: PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.TOTAL_AMOUNT,
  },
  {
    label: 'نرخ سود',
    accessor: PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.INTEREST_RATE,
  },
  {
    label: 'نوع تعهدات',
    accessor: PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.COMMITMENT_TYPE,
  },
  {
    label: 'وضعیت',
    accessor: PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.STATUS,
  },
  {
    label: 'شماره قرارداد بانک مرکزی',
    accessor: PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.CENTRAL_BANK_CONTRACT_NUMBER,
  },
  {
    label: 'تاریخ تخصیص',
    accessor: PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.ALLOCATION_DATE,
  },
  {
    label: 'تاریخ پایان',
    accessor: PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.END_DATE,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN,
  },
  {
    label: 'کدشعبه تعهدات',
    accessor: PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.BRANCH_CODE,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN,
  },
  {
    label: 'نام شعبه تعهدات',
    accessor: PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.BRANCH_NAME,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN,
  },
  {
    label: 'نام منطقه',
    accessor: PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.REGION_NAME,
    renderType: TABLE_RENDER_TYPES.EXTRA_COLUMN,
  },
  ACTIONS_COLUMN,
];

export const PANEL_INDIVIDUAL_COMMITMENTS_TABLE_FAKE_DATA = [
  {
    id: 1,
    [PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.INDIRECT_COMMITMENT]: 'بله',
    [PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.COMMITMENT_NUMBER]: 'COM-1403001',
    [PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.PRINCIPAL_AMOUNT]: '3,000,000,000 ریال',
    [PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.TOTAL_AMOUNT]: '3,450,000,000 ریال',
    [PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.INTEREST_RATE]: '15%',
    [PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.COMMITMENT_TYPE]: 'ضمانت نامه',
    [PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.STATUS]: (
      <Tag text='فعال' color='green' variant='fade'/>
    ),
    [PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.CENTRAL_BANK_CONTRACT_NUMBER]: 'CB-987654',
    [PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.ALLOCATION_DATE]: '1402/04/20',
    [PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.END_DATE]: '1404/04/20',
    [PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.BRANCH_CODE]: '1102',
    [PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.BRANCH_NAME]: 'شعبه ونک',
    [PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.REGION_NAME]: 'منطقه شمال',
  },
  {
    id: 2,
    [PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.INDIRECT_COMMITMENT]: 'خیر',
    [PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.COMMITMENT_NUMBER]: 'COM-1403002',
    [PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.PRINCIPAL_AMOUNT]: '1,200,000,000 ریال',
    [PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.TOTAL_AMOUNT]: '1,350,000,000 ریال',
    [PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.INTEREST_RATE]: '12%',
    [PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.COMMITMENT_TYPE]: 'اعتبار اسنادی',
    [PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.STATUS]: (
      <Tag text='پایان یافته' color='blue' variant='fade'/>
    ),
    [PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.CENTRAL_BANK_CONTRACT_NUMBER]: 'CB-123456',
    [PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.ALLOCATION_DATE]: '1400/09/10',
    [PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.END_DATE]: '1403/09/10',
    [PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.BRANCH_CODE]: '2045',
    [PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.BRANCH_NAME]: 'شعبه انقلاب',
    [PANEL_INDIVIDUAL_COMMITMENTS_TABLE_COLUMNS_KEYS.REGION_NAME]: 'منطقه غرب',
  },
];
